#include "axiomtrace.h"

#include <stdint.h>
#include <stdio.h>

static int failures;

#define CHECK_VALUE(name, actual, expected) \
    do { \
        if ((uint32_t)(actual) != (uint32_t)(expected)) { \
            printf("FAIL: %s actual=%lu expected=%lu\n", \
                   (name), (unsigned long)(uint32_t)(actual), (unsigned long)(uint32_t)(expected)); \
            failures++; \
        } \
    } while (0)

int main(void) {
    CHECK_VALUE("AXIOM_PRESET", AXIOM_PRESET, EXPECT_PRESET);
    CHECK_VALUE("AXIOM_PROFILE", AXIOM_PROFILE, EXPECT_PROFILE);
    CHECK_VALUE("AXIOM_RING_BUFFER_SIZE", AXIOM_RING_BUFFER_SIZE, EXPECT_RING_BUFFER_SIZE);
    CHECK_VALUE("AXIOM_MAX_PAYLOAD_LEN", AXIOM_MAX_PAYLOAD_LEN, EXPECT_MAX_PAYLOAD_LEN);
    CHECK_VALUE("AXIOM_MODULE_MAX", AXIOM_MODULE_MAX, EXPECT_MODULE_MAX);
    CHECK_VALUE("AXIOM_CFG_LOCATION_MODE", AXIOM_CFG_LOCATION_MODE, EXPECT_LOCATION_MODE);
    CHECK_VALUE("AXIOM_CFG_TIME_SYNC_ENABLED", AXIOM_CFG_TIME_SYNC_ENABLED, EXPECT_TIME_SYNC_ENABLED);
    CHECK_VALUE("AXIOM_SHORT_CS", AXIOM_SHORT_CS, EXPECT_SHORT_CS);
    CHECK_VALUE("AXIOM_BACKEND_DEGRADATION", AXIOM_BACKEND_DEGRADATION, EXPECT_BACKEND_DEGRADATION);
    CHECK_VALUE("AXIOM_CAPSULE_ENABLED", AXIOM_CAPSULE_ENABLED, EXPECT_CAPSULE_ENABLED);
    CHECK_VALUE("AXIOM_CAPSULE_PRE_EVENTS", AXIOM_CAPSULE_PRE_EVENTS, EXPECT_CAPSULE_PRE_EVENTS);
    CHECK_VALUE("AXIOM_CAPSULE_POST_EVENTS", AXIOM_CAPSULE_POST_EVENTS, EXPECT_CAPSULE_POST_EVENTS);
    CHECK_VALUE("AXIOM_CAPSULE_RING_SIZE", AXIOM_CAPSULE_RING_SIZE, EXPECT_CAPSULE_RING_SIZE);
    CHECK_VALUE("AXIOM_RING_BUFFER_POLICY", AXIOM_RING_BUFFER_POLICY, EXPECT_RING_BUFFER_POLICY);
    CHECK_VALUE("AXIOM_ENCODE_OVERFLOW_DETECTION", AXIOM_ENCODE_OVERFLOW_DETECTION, EXPECT_ENCODE_OVERFLOW_DETECTION);
    CHECK_VALUE("AXIOM_SELFTEST", AXIOM_SELFTEST, EXPECT_SELFTEST);
    CHECK_VALUE("AXIOM_DEBUG", AXIOM_DEBUG, EXPECT_DEBUG);
#if AXIOM_BACKEND_DEGRADATION
    CHECK_VALUE("AXIOM_BACKEND_FAIL_THRESHOLD", AXIOM_BACKEND_FAIL_THRESHOLD, EXPECT_BACKEND_FAIL_THRESHOLD);
    CHECK_VALUE("AXIOM_BACKEND_RECOVERY_US", AXIOM_BACKEND_RECOVERY_US, EXPECT_BACKEND_RECOVERY_US);
#endif
    CHECK_VALUE("AXIOM_CAPSULE_MAX_SNAPSHOT_LEN", AXIOM_CAPSULE_MAX_SNAPSHOT_LEN, EXPECT_CAPSULE_MAX_SNAPSHOT_LEN);
    CHECK_VALUE("AXIOM_CAPSULE_FLASH_SIZE", AXIOM_CAPSULE_FLASH_SIZE, EXPECT_CAPSULE_FLASH_SIZE);

    if (failures == 0) {
        printf("test_config_presets: PASSED\n");
    }
    return failures;
}
