/* ============================================================================
 * AxiomTrace Single-File Amalgamated Library
 * Auto-generated by tool/scripts/amalgamate.py
 * ============================================================================ */

#ifndef AXIOMTRACE_H
#define AXIOMTRACE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ===== axiom_static_assert.h ===== */
#ifndef AXIOM_STATIC_ASSERT_H
#define AXIOM_STATIC_ASSERT_H

/* ---------------------------------------------------------------------------
 * Compile-time assertions (C11 _Static_assert wrapper)
 * --------------------------------------------------------------------------- */

#define AXIOM_STATIC_ASSERT(expr, msg) _Static_assert((expr), msg)

#define AXIOM_CHECK_SIZE(type, expected) \
    AXIOM_STATIC_ASSERT(sizeof(type) == (expected), #type " size mismatch")

#define AXIOM_CHECK_ALIGN(type, align) \
    AXIOM_STATIC_ASSERT(_Alignof(type) == (align), #type " align mismatch")

#define AXIOM_CHECK_FIELD_OFFSET(type, field, expected) \
    AXIOM_STATIC_ASSERT(__builtin_offsetof(type, field) == (expected), #type "." #field " offset mismatch")

#define AXIOM_CHECK_RANGE(val, min, max) \
    AXIOM_STATIC_ASSERT((val) >= (min) && (val) <= (max), #val " out of range")

#define AXIOM_CHECK_POWER_OF_TWO(val) \
    AXIOM_STATIC_ASSERT(((val) != 0) && (((val) & ((val) - 1)) == 0), #val " must be power of two")

#define AXIOM_CHECK_ARRAY_SIZE(arr, expected) \
    AXIOM_STATIC_ASSERT((sizeof(arr) / sizeof((arr)[0])) == (expected), #arr " size mismatch")

#endif /* AXIOM_STATIC_ASSERT_H */

/* ===== axiom_config.h ===== */
#ifndef AXIOM_CONFIG_H
#define AXIOM_CONFIG_H

#include <stdint.h>

/* ---------------------------------------------------------------------------
 * Library Version (SemVer 2.0.0)
 * Bump on release. Checked at compile-time by downstream consumers.
 * --------------------------------------------------------------------------- */
#define AXIOMTRACE_VERSION_MAJOR 0u
#define AXIOMTRACE_VERSION_MINOR 1u
#define AXIOMTRACE_VERSION_PATCH 0u

/* Compile-time version check: AXIOMTRACE_VERSION_CHECK(0,1,0) */
#define AXIOMTRACE_VERSION_CHECK(ma, mi, pa) \
    ((AXIOMTRACE_VERSION_MAJOR > (ma)) ||    \
     (AXIOMTRACE_VERSION_MAJOR == (ma) && AXIOMTRACE_VERSION_MINOR > (mi)) || \
     (AXIOMTRACE_VERSION_MAJOR == (ma) && AXIOMTRACE_VERSION_MINOR == (mi) && \
      AXIOMTRACE_VERSION_PATCH >= (pa)))

/* ---------------------------------------------------------------------------
 * Compiler Helpers
 * --------------------------------------------------------------------------- */

/* Mark a symbol as deprecated with a migration hint.
 * Example: AXIOM_DEPRECATED("use axiom_new_api() instead") */
#if defined(__GNUC__) || defined(__clang__)
#define AXIOM_DEPRECATED(msg) __attribute__((deprecated(msg)))
#elif defined(_MSC_VER)
#define AXIOM_DEPRECATED(msg) __declspec(deprecated(msg))
#elif defined(__IAR_SYSTEMS_ICC__)
#define AXIOM_DEPRECATED(msg) _Pragma("message=\"" msg "\"")
#else
#define AXIOM_DEPRECATED(msg)
#endif

/* ---------------------------------------------------------------------------
 * Core Configuration
 * --------------------------------------------------------------------------- */

/* Main ring buffer size. MUST be a power of two. */
#ifndef AXIOM_RING_BUFFER_SIZE
#define AXIOM_RING_BUFFER_SIZE 4096u
#endif

/* DROP: Discard new events when full. 
 * OVERWRITE: Overwrite oldest events when full (maintains O(1)). */
#define AXIOM_RING_BUFFER_POLICY_DROP      0
#define AXIOM_RING_BUFFER_POLICY_OVERWRITE 1

#ifndef AXIOM_RING_BUFFER_POLICY
#define AXIOM_RING_BUFFER_POLICY AXIOM_RING_BUFFER_POLICY_DROP
#endif

/* Maximum payload size per event in bytes. */
#ifndef AXIOM_MAX_PAYLOAD_LEN
#define AXIOM_MAX_PAYLOAD_LEN 128u
#endif

/* Maximum number of unique module IDs (0 .. AXIOM_MODULE_MAX-1).
 * Determines the width of the module filter bitmask. */
#ifndef AXIOM_MODULE_MAX
#define AXIOM_MODULE_MAX 32u
#endif

/* ---------------------------------------------------------------------------
 * Observability Extensions
 * --------------------------------------------------------------------------- */

/* If enabled, every AX_EVT will automatically append __LINE__ and a hash of __FILE__.
 * Adds approximately 4 bytes of payload per event. */
#ifndef AXIOM_CFG_USE_LOCATION
#define AXIOM_CFG_USE_LOCATION 0
#endif

/* If enabled, the core will periodically (or manually) emit sync events 
 * to map local counters to host-provided Unix time. */
#ifndef AXIOM_CFG_TIME_SYNC_ENABLED
#define AXIOM_CFG_TIME_SYNC_ENABLED 1
#endif

#endif /* AXIOM_CONFIG_H */

/* ===== axiom_port.h ===== */
#ifndef AXIOM_PORT_H
#define AXIOM_PORT_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Port layer — override by providing strong-symbol implementations.
 * Default weak implementations are in axiom_port_generic.c.
 * --------------------------------------------------------------------------- */

/* Monotonic timestamp in microseconds (wraps naturally) */
extern uint32_t axiom_port_timestamp(void);

/* Critical section: must be nestable or simply disable/enable IRQs */
extern void axiom_port_critical_enter(void);
extern void axiom_port_critical_exit(void);

/* String output for development logs (AX_LOG). May be UART/RTT/stdout. */
extern void axiom_port_string_out(const char *str);

/* Fault hook: called on AX_FAULT events. Override to customize behavior. */
extern void axiom_port_fault_hook(uint8_t module_id, uint16_t event_id,
                                   const uint8_t *payload, uint8_t payload_len);

/* Register snapshot for fault capsule. Returns bytes written. */
extern uint8_t axiom_port_fault_snapshot(uint8_t *buf, uint8_t max_len);

/* Flash operations for capsule backend (non-ISR only) */
extern int axiom_port_flash_erase(uint32_t addr, uint32_t len);
extern int axiom_port_flash_write(uint32_t addr, const uint8_t *data, uint32_t len);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_PORT_H */

/* ===== axiom_event.h ===== */
#ifndef AXIOM_EVENT_H
#define AXIOM_EVENT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Log levels
 * --------------------------------------------------------------------------- */
typedef enum {
    AXIOM_LEVEL_DEBUG = 0,
    AXIOM_LEVEL_INFO  = 1,
    AXIOM_LEVEL_WARN  = 2,
    AXIOM_LEVEL_ERROR = 3,
    AXIOM_LEVEL_FAULT = 4,
    AXIOM_LEVEL_MAX   = 5
} axiom_level_t;

/* ---------------------------------------------------------------------------
 * Event header: exactly 8 bytes, packed, little-endian on wire
 * --------------------------------------------------------------------------- */
typedef struct __attribute__((packed)) {
    uint8_t  sync;       /* 0xA5 */
    uint8_t  version;    /* major << 4 | minor */
    uint8_t  level;      /* lower nibble: level, upper nibble: reserved (0) */
    uint8_t  module_id;
    uint16_t event_id;   /* little-endian */
    uint16_t seq;        /* little-endian */
} axiom_event_header_t;

AXIOM_CHECK_SIZE(axiom_event_header_t, 8);
AXIOM_CHECK_ALIGN(axiom_event_header_t, 1);

/* ---------------------------------------------------------------------------
 * Payload type tags (self-describing)
 * --------------------------------------------------------------------------- */
#define AXIOM_TYPE_BOOL      0x00u
#define AXIOM_TYPE_U8        0x01u
#define AXIOM_TYPE_I8        0x02u
#define AXIOM_TYPE_U16       0x03u
#define AXIOM_TYPE_I16       0x04u
#define AXIOM_TYPE_U32       0x05u
#define AXIOM_TYPE_I32       0x06u
#define AXIOM_TYPE_F32       0x07u
#define AXIOM_TYPE_TIMESTAMP 0x08u
#define AXIOM_TYPE_BYTES     0x09u

/* Reserved for future standard types: 0x0A - 0x7F */
/* User-defined types: 0x80 - 0xFF */

/* ---------------------------------------------------------------------------
 * Wire format version v1.0
 * --------------------------------------------------------------------------- */
#define AXIOM_WIRE_VERSION_MAJOR 1u
#define AXIOM_WIRE_VERSION_MINOR 0u
#define AXIOM_WIRE_VERSION ((uint8_t)((AXIOM_WIRE_VERSION_MAJOR << 4u) | AXIOM_WIRE_VERSION_MINOR))

/* ---------------------------------------------------------------------------
 * Frame limits (AXIOM_MAX_PAYLOAD_LEN defined in axiom_config.h)
 * --------------------------------------------------------------------------- */

/* Max timestamp length is 5 bytes (0xFE + 4-byte full delta) */
#define AXIOM_MAX_FRAME_LEN (8u + 5u + 1u + AXIOM_MAX_PAYLOAD_LEN + 2u)

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_EVENT_H */

/* ===== axiom_encode.h ===== */
#ifndef AXIOM_ENCODE_H
#define AXIOM_ENCODE_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Type-safe payload encoding helpers
 * Each function writes: [type_tag (1B)] [value (N bytes)]
 * --------------------------------------------------------------------------- */

static inline void axiom_enc_bool(uint8_t *buf, uint8_t *pos, bool val) {
    buf[(*pos)++] = AXIOM_TYPE_BOOL;
    buf[(*pos)++] = val ? 1u : 0u;
}

static inline void axiom_enc_u8(uint8_t *buf, uint8_t *pos, uint8_t val) {
    buf[(*pos)++] = AXIOM_TYPE_U8;
    buf[(*pos)++] = val;
}

static inline void axiom_enc_i8(uint8_t *buf, uint8_t *pos, int8_t val) {
    buf[(*pos)++] = AXIOM_TYPE_I8;
    buf[(*pos)++] = (uint8_t)val;
}

static inline void axiom_enc_u16(uint8_t *buf, uint8_t *pos, uint16_t val) {
    buf[(*pos)++] = AXIOM_TYPE_U16;
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)(val >> 8);
}

static inline void axiom_enc_i16(uint8_t *buf, uint8_t *pos, int16_t val) {
    buf[(*pos)++] = AXIOM_TYPE_I16;
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)((uint16_t)val >> 8);
}

static inline void axiom_enc_u32(uint8_t *buf, uint8_t *pos, uint32_t val) {
    buf[(*pos)++] = AXIOM_TYPE_U32;
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(val >> 24);
}

static inline void axiom_enc_i32(uint8_t *buf, uint8_t *pos, int32_t val) {
    uint32_t u = (uint32_t)val;
    buf[(*pos)++] = AXIOM_TYPE_I32;
    buf[(*pos)++] = (uint8_t)(u & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(u >> 24);
}

static inline void axiom_enc_f32(uint8_t *buf, uint8_t *pos, float val) {
    buf[(*pos)++] = AXIOM_TYPE_F32;
    uint32_t u;
    memcpy(&u, &val, sizeof(u));
    buf[(*pos)++] = (uint8_t)(u & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(u >> 24);
}

static inline void axiom_enc_timestamp(uint8_t *buf, uint8_t *pos, uint32_t val) {
    buf[(*pos)++] = AXIOM_TYPE_TIMESTAMP;
    /* Write raw 32-bit value (no duplicate type tag — unlike the other enc helpers) */
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(val >> 24);
}

static inline void axiom_enc_bytes(uint8_t *buf, uint8_t *pos, const uint8_t *data, uint8_t len) {
    buf[(*pos)++] = AXIOM_TYPE_BYTES;
    buf[(*pos)++] = len;
    for (uint8_t i = 0; i < len; ++i) {
        buf[(*pos)++] = data[i];
    }
}

/* ---------------------------------------------------------------------------
 * C11 _Generic dispatcher for a single argument
 * Note: double literals (e.g., 3.14) are NOT supported.
 * Use float literals (e.g., 3.14f) or explicit (float)3.14 cast.
 * --------------------------------------------------------------------------- */
#define _AXIOM_ENCODE_ONE(buf, pos, arg) \
    _Generic((arg), \
        bool:     axiom_enc_bool, \
        uint8_t:  axiom_enc_u8,  \
        int8_t:   axiom_enc_i8,  \
        uint16_t: axiom_enc_u16, \
        int16_t:  axiom_enc_i16, \
        uint32_t: axiom_enc_u32, \
        int32_t:  axiom_enc_i32, \
        float:    axiom_enc_f32  \
    )(buf, &(pos), arg)

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_ENCODE_H */

/* ===== axiom_crc.h ===== */
#ifndef AXIOM_CRC_H
#define AXIOM_CRC_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * CRC-16/CCITT-FALSE
 * poly = 0x1021, init = 0xFFFF, no reflection, final XOR = 0x0000
 * --------------------------------------------------------------------------- */

uint16_t axiom_crc16(const uint8_t *data, size_t len);

/* Lookup table (256 bytes, stored in ROM) */
extern const uint16_t axiom_crc16_table[256];

/* Incremental CRC update */
static inline uint16_t axiom_crc16_update(uint16_t crc, uint8_t data) {
    return (uint16_t)((crc << 8) ^ axiom_crc16_table[((crc >> 8) ^ data) & 0xFFu]);
}

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_CRC_H */

/* ===== axiom_ring.h ===== */
#ifndef AXIOM_RING_H
#define AXIOM_RING_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifndef AXIOM_RING_BUFFER_POLICY_DROP
#define AXIOM_RING_BUFFER_POLICY_DROP 0
#endif

#ifndef AXIOM_RING_BUFFER_POLICY_OVERWRITE
#define AXIOM_RING_BUFFER_POLICY_OVERWRITE 1
#endif

#ifndef AXIOM_RING_BUFFER_POLICY
#define AXIOM_RING_BUFFER_POLICY AXIOM_RING_BUFFER_POLICY_DROP
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * IRQ-safe SPSC RAM Ring Buffer with critical-section protection.
 * Single-producer (ISR or main loop), single-consumer (backend drain).
 * --------------------------------------------------------------------------- */

typedef struct {
    volatile uint32_t head;
    volatile uint32_t tail;
    uint32_t capacity;
    uint32_t mask;
    uintptr_t reserved;
} axiom_ring_t;

/* Initialize ring buffer in the provided memory block. 
 * 'size' must be a power of two. */
void axiom_ring_init(axiom_ring_t *ring, uint8_t *buf, uint32_t size);

/* Write data to ring. Returns true on success, false if dropped. */
bool axiom_ring_write(axiom_ring_t *ring, const uint8_t *data, uint16_t len);

/* Write a chunk to the ring and optionally update CRC.
 * Internal use only, requires caller to handle critical section and capacity check. */
void axiom_ring_write_chunk(axiom_ring_t *ring, const uint8_t *data, uint16_t len, uint16_t *crc);

/* Read up to max_len bytes from ring. Returns bytes read. */
uint16_t axiom_ring_read(axiom_ring_t *ring, uint8_t *out, uint16_t max_len);

/* Peek at data without consuming. Returns bytes available. */
uint16_t axiom_ring_peek(const axiom_ring_t *ring, uint8_t *out, uint16_t max_len);

/* Advance tail by 'n' bytes without copying data.
 * Caller must have already read the data (e.g., via axiom_ring_peek).
 * Caller must ensure n <= axiom_ring_used(). */
void axiom_ring_consume(axiom_ring_t *ring, uint16_t n);

/* Bytes currently stored */
static inline uint32_t axiom_ring_used(const axiom_ring_t *ring) {
    return ring->head - ring->tail;
}

/* Free space */
static inline uint32_t axiom_ring_free(const axiom_ring_t *ring) {
    return ring->capacity - (ring->head - ring->tail);
}

/* Reset ring to empty */
void axiom_ring_reset(axiom_ring_t *ring);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_RING_H */

/* ===== axiom_timestamp.h ===== */
#ifndef AXIOM_TIMESTAMP_H
#define AXIOM_TIMESTAMP_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Compressed relative timestamp
 * Stores delta from previous event to reduce payload size.
 * --------------------------------------------------------------------------- */

typedef struct {
    uint32_t last_raw;
    uint32_t baseline; /* Reserved for future time-sync anchor (Unix epoch mapping) */
} axiom_timestamp_ctx_t;

/* Initialize timestamp context */
void axiom_timestamp_init(axiom_timestamp_ctx_t *ctx);

/* Encode current timestamp into up to 5 bytes. Returns encoded length (1..5). */
uint8_t axiom_timestamp_encode(axiom_timestamp_ctx_t *ctx, uint8_t *out);

/* Decode timestamp length from the first byte after the frame header.
 * Returns 1, 2, 3, or 5. Call this on frame[8] to locate payload_len.
 */
static inline uint8_t axiom_timestamp_decode_len(uint8_t first_byte) {
    if (first_byte >= 0xC0) {
        /* 0xFE and 0xFF both signal 5-byte full-delta encoding.
         * 0xC0..0xFD are 3-byte encoding (21-bit delta). */
        return (first_byte >= 0xFEu) ? 5 : 3;
    } else if (first_byte >= 0x80) {
        return 2;
    }
    return 1;
}

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_TIMESTAMP_H */

/* ===== axiom_filter.h ===== */
#ifndef AXIOM_FILTER_H
#define AXIOM_FILTER_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Runtime level/module filter and drop statistics
 * --------------------------------------------------------------------------- */

typedef struct {
    volatile uint32_t level_mask;   /* May be read in ISR context */
    volatile uint32_t module_mask;  /* May be read in ISR context */
    uint32_t drop_count;        /* Total dropped events */
    uint8_t  drop_module;       /* Module ID of last dropped event */
    uint16_t drop_event;        /* Event ID of last dropped event */
    bool     drop_pending;      /* True if drops occurred since last summary */
} axiom_filter_t;

/* Initialize filter (all levels/modules enabled, counters zeroed) */
void axiom_filter_init(axiom_filter_t *filter);

/* Check if event passes filter. Returns true if should emit. */
bool axiom_filter_check(axiom_filter_t *filter, axiom_level_t level, uint8_t module_id);

/* Record a drop. Call when event is discarded. */
void axiom_filter_drop(axiom_filter_t *filter, uint8_t module_id, uint16_t event_id);

/* Check and clear drop_pending flag. Returns true if a DROP_SUMMARY should be emitted.
 * Note: Drop summary is currently handled internally by axiom_write().
 * These functions are provided for external consumers (e.g., custom backends,
 * test harnesses) that need direct access to drop statistics. */
bool axiom_filter_drop_summary_ready(axiom_filter_t *filter);

/* Get drop counter and reset.
 * Provided for external consumers — see note above. */
uint32_t axiom_filter_drop_count_get_and_clear(axiom_filter_t *filter);

/* Runtime filter control — implementations are in axiom_event.c where s_filter is defined */
void axiom_level_mask_set(uint32_t mask);
uint32_t axiom_level_mask_get(void);
void axiom_module_mask_set(uint32_t mask);
uint32_t axiom_module_mask_get(void);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_FILTER_H */

/* ===== axiom_frontend.h ===== */
#ifndef AXIOM_FRONTEND_H
#define AXIOM_FRONTEND_H


#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Profile control
 * --------------------------------------------------------------------------- */
#define AXIOM_PROFILE_DEV    0
#define AXIOM_PROFILE_FIELD  1
#define AXIOM_PROFILE_PROD   2

#ifndef AXIOM_PROFILE
#define AXIOM_PROFILE AXIOM_PROFILE_DEV
#endif

/* ---------------------------------------------------------------------------
 * Variadic argument counting (GCC/Clang/MSVC compatible)
 * --------------------------------------------------------------------------- */
#define _AXIOM_ARG_N(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, N, ...) N
#define _AXIOM_NARG_(...) _AXIOM_ARG_N(__VA_ARGS__)
#define _AXIOM_NARG(...) _AXIOM_NARG_(0, ##__VA_ARGS__, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

#define _AXIOM_CONCAT2(a, b) a ## b
#define _AXIOM_CONCAT(a, b)  _AXIOM_CONCAT2(a, b)

/* ---------------------------------------------------------------------------
 * Core write declaration (defined in axiom_event.c)
 * --------------------------------------------------------------------------- */
void axiom_write(axiom_level_t level, uint8_t module_id, uint16_t event_id,
                 const uint8_t *payload, uint8_t payload_len);
void axiom_init(void);
void axiom_flush(void);

/* Runtime filter control — declared in axiom_filter.h, exposed here for convenience.
 * void axiom_level_mask_set(uint32_t mask);
 * uint32_t axiom_level_mask_get(void);
 * void axiom_module_mask_set(uint32_t mask);
 * uint32_t axiom_module_mask_get(void);
 */

/* ---------------------------------------------------------------------------
 * FNV-1a 16-bit hash (runtime, for key hashing)
 * --------------------------------------------------------------------------- */
static inline uint16_t _axiom_fnv1a_16(const char *s) {
    uint16_t h = 0x811cu;
    while (*s) {
        h ^= (uint16_t)(unsigned char)(*s++);
        h *= 0x0103u;
    }
    return h;
}

/* ---------------------------------------------------------------------------
 * AX_EVT — Structured Event (always compiled, all profiles)
 * --------------------------------------------------------------------------- */
#define _AXIOM_EVT_0(level, mod, evt) \
    axiom_write((level), (mod), (evt), NULL, 0)

#define _AXIOM_EVT_1(level, mod, evt, a1) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_2(level, mod, evt, a1, a2) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_3(level, mod, evt, a1, a2, a3) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_4(level, mod, evt, a1, a2, a3, a4) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_5(level, mod, evt, a1, a2, a3, a4, a5) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_6(level, mod, evt, a1, a2, a3, a4, a5, a6) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_ENCODE_ONE(_b, _p, a6); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_7(level, mod, evt, a1, a2, a3, a4, a5, a6, a7) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_ENCODE_ONE(_b, _p, a6); \
         _AXIOM_ENCODE_ONE(_b, _p, a7); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_8(level, mod, evt, a1, a2, a3, a4, a5, a6, a7, a8) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_ENCODE_ONE(_b, _p, a6); \
         _AXIOM_ENCODE_ONE(_b, _p, a7); \
         _AXIOM_ENCODE_ONE(_b, _p, a8); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_DISPATCH(level, mod, evt, ...) \
    _AXIOM_CONCAT(_AXIOM_EVT_, _AXIOM_NARG(__VA_ARGS__))(level, mod, evt, ##__VA_ARGS__)

#define AX_EVT(level, mod, evt, ...) \
    _AXIOM_EVT_DISPATCH(AXIOM_LEVEL_##level, mod, evt, ##__VA_ARGS__)

#define AX_FAULT(mod, evt, ...) \
    _AXIOM_EVT_DISPATCH(AXIOM_LEVEL_FAULT, mod, evt, ##__VA_ARGS__)

/* ---------------------------------------------------------------------------
 * AX_LOG — Development logging (PROD profile = no-op)
 * Outputs plain text via axiom_port_string_out(). Does NOT enter binary protocol.
 * --------------------------------------------------------------------------- */
#if (AXIOM_PROFILE == AXIOM_PROFILE_DEV) || (AXIOM_PROFILE == AXIOM_PROFILE_FIELD)

#define AX_LOG(msg)         do { axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_DEBUG(msg)   do { axiom_port_string_out("[DEBUG] "); axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_INFO(msg)    do { axiom_port_string_out("[INFO] ");  axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_WARN(msg)    do { axiom_port_string_out("[WARN] ");  axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_ERROR(msg)   do { axiom_port_string_out("[ERROR] "); axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)

#else /* PROD */

#define AX_LOG(msg)         ((void)0)
#define AX_LOG_DEBUG(msg)   ((void)0)
#define AX_LOG_INFO(msg)    ((void)0)
#define AX_LOG_WARN(msg)    ((void)0)
#define AX_LOG_ERROR(msg)   ((void)0)

#endif

/* ---------------------------------------------------------------------------
 * AX_PROBE — Timing probe (PROD profile = no-op)
 * Writes minimal structured event with a 16-bit tag hash + value.
 * --------------------------------------------------------------------------- */
#if (AXIOM_PROFILE == AXIOM_PROFILE_DEV) || (AXIOM_PROFILE == AXIOM_PROFILE_FIELD)

#define AX_PROBE(tag, value) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         uint16_t _th = _axiom_fnv1a_16(tag); \
         axiom_enc_u16(_b, &_p, _th); \
         _AXIOM_ENCODE_ONE(_b, _p, value); \
         axiom_write(AXIOM_LEVEL_DEBUG, 0, 0, _b, _p); } while(0)

#else /* PROD */

#define AX_PROBE(tag, value) ((void)0)

#endif

/* ---------------------------------------------------------------------------
 * AX_KV — Key-Value event (always compiled)
 * Keys are hashed at compile-time to 16-bit IDs via FNV-1a.
 * --------------------------------------------------------------------------- */
#define _AXIOM_KV_KEYVAL(buf, pos, key, val) \
    do { uint16_t _kh = _axiom_fnv1a_16(key); \
         axiom_enc_u16(buf, &(pos), _kh); \
         _AXIOM_ENCODE_ONE(buf, pos, val); \
    } while(0)

#define _AXIOM_KV_2(level, mod, evt, k1, v1) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_KV_KEYVAL(_b, _p, k1, v1); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_KV_4(level, mod, evt, k1, v1, k2, v2) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_KV_KEYVAL(_b, _p, k1, v1); \
         _AXIOM_KV_KEYVAL(_b, _p, k2, v2); \
         axiom_write((level), (mod), (evt), _b, _p); } while(0)

#define AX_KV(level, mod, evt, ...) \
    _AXIOM_CONCAT(_AXIOM_KV_, _AXIOM_NARG(__VA_ARGS__))(AXIOM_LEVEL_##level, mod, evt, ##__VA_ARGS__)

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_FRONTEND_H */

/* ===== axiom_backend.h ===== */
#ifndef AXIOM_BACKEND_H
#define AXIOM_BACKEND_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Backend Capability Flags
 * Used by the backend registry to advertise transport capabilities.
 * Query via backend.caps at registration or discovery time.
 * --------------------------------------------------------------------------- */
#define AXIOM_BACKEND_CAP_MEMORY  (1u << 0) /* In-memory ring capture           */
#define AXIOM_BACKEND_CAP_UART    (1u << 1) /* Serial UART transport            */
#define AXIOM_BACKEND_CAP_USB     (1u << 2) /* USB CDC / bulk transport          */
#define AXIOM_BACKEND_CAP_RTT     (1u << 3) /* SEGGER RTT transport             */
#define AXIOM_BACKEND_CAP_SWO     (1u << 4) /* ARM SWO stimulus port            */
#define AXIOM_BACKEND_CAP_CANFD   (1u << 5) /* CAN-FD transport                 */
#define AXIOM_BACKEND_CAP_CAPSULE (1u << 6) /* Fault capsule (flash-persistent) */

/* ---------------------------------------------------------------------------
 * Backend Contract
 * The first field `size` enables forward-compatible struct evolution:
 * - Old backends (zero-initialized) have size==0, treated as legacy v1 layout.
 * - New backends set size via AXIOM_BACKEND_INIT() so the registry can
 *   detect the layout version and safely access fields added in future minor
 *   releases without breaking ABI.
 * --------------------------------------------------------------------------- */
typedef struct {
    uint16_t size;              /* sizeof(this struct) at compile time */
    const char *name;
    uint32_t caps;

    int  (*write)(const uint8_t *buf, uint16_t len, void *ctx);
    int  (*ready)(void *ctx);
    int  (*flush)(void *ctx);
    int  (*panic_write)(const uint8_t *buf, uint16_t len, void *ctx);

    void (*on_drop)(uint32_t lost, void *ctx);
    void *ctx;
} axiom_backend_t;

/* Designated-initializer wrapper: fills size automatically.
 * Example: static const axiom_backend_t my_be = AXIOM_BACKEND_INIT(
 *     .name = "uart", .write = uart_write, .ctx = &uart_ctx); */
#define AXIOM_BACKEND_INIT(...)  { .size = sizeof(axiom_backend_t), __VA_ARGS__ }

/* ---------------------------------------------------------------------------
 * Backend Registry
 * --------------------------------------------------------------------------- */

#ifndef AXIOM_BACKEND_MAX
#define AXIOM_BACKEND_MAX 4
#endif

/* Register a backend. Returns 0 on success, negative on error.
 * MUST be called before any axiom_write() — not thread-safe. */
int axiom_backend_register(const axiom_backend_t *backend);

/* Dispatch a frame to all registered backends.
 * Called internally by axiom_write() after ring buffer insertion. */
void axiom_backend_dispatch(const uint8_t *frame, uint16_t len);

/* Flush all backends that provide a flush callback. */
void axiom_backend_flush_all(void);

/* Panic write to all backends that provide panic_write. */
void axiom_backend_panic_write(const uint8_t *frame, uint16_t len);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_BACKEND_H */

/* ===== axiom_port_generic.c ===== */

/* ============================================================================
 * Generic host/default port implementations
 * ============================================================================
 *
 * On ELF targets (Linux, most embedded GCC toolchains), these symbols are
 * marked weak so the user can override them by providing strong-symbol
 * implementations in another translation unit.
 *
 * On Windows/PE targets (MinGW, MSVC), weak symbol support is limited or
 * non-existent. We therefore provide regular (strong) defaults.  If you need
 * to override on Windows, either:
 *   1. Edit this file directly, or
 *   2. Provide an object file with the same symbols **before** this one in
 *      the link command.
 * ============================================================================ */

#if (defined(__GNUC__) || defined(__clang__)) && !defined(_WIN32)
#define AXIOM_WEAK __attribute__((weak))
#else
#define AXIOM_WEAK
#endif

AXIOM_WEAK uint32_t axiom_port_timestamp(void) { return 0u; }

/* NOTE: Default no-op implementation. Override for production builds
 * to provide proper interrupt masking (e.g., __disable_irq/__enable_irq
 * on ARM Cortex-M). Without override, concurrent axiom_write() calls
 * will corrupt the ring buffer. */
AXIOM_WEAK void axiom_port_critical_enter(void) { }

AXIOM_WEAK void axiom_port_critical_exit(void) { }

AXIOM_WEAK void axiom_port_string_out(const char *str) {
    (void)str;
}

AXIOM_WEAK void axiom_port_fault_hook(uint8_t module_id, uint16_t event_id,
                                       const uint8_t *payload, uint8_t payload_len) {
    (void)module_id; (void)event_id; (void)payload; (void)payload_len;
}

AXIOM_WEAK uint8_t axiom_port_fault_snapshot(uint8_t *buf, uint8_t max_len) {
    (void)buf; (void)max_len;
    return 0;
}

AXIOM_WEAK int axiom_port_flash_erase(uint32_t addr, uint32_t len) {
    (void)addr; (void)len;
    return -1;
}

AXIOM_WEAK int axiom_port_flash_write(uint32_t addr, const uint8_t *data, uint32_t len) {
    (void)addr; (void)data; (void)len;
    return -1;
}

/* ===== axiom_crc.c ===== */

/* CRC-16/CCITT-FALSE lookup table */
const uint16_t axiom_crc16_table[256] = {
    0x0000, 0x1021, 0x2042, 0x3063, 0x4084, 0x50A5, 0x60C6, 0x70E7,
    0x8108, 0x9129, 0xA14A, 0xB16B, 0xC18C, 0xD1AD, 0xE1CE, 0xF1EF,
    0x1231, 0x0210, 0x3273, 0x2252, 0x52B5, 0x4294, 0x72F7, 0x62D6,
    0x9339, 0x8318, 0xB37B, 0xA35A, 0xD3BD, 0xC39C, 0xF3FF, 0xE3DE,
    0x2462, 0x3443, 0x0420, 0x1401, 0x64E6, 0x74C7, 0x44A4, 0x5485,
    0xA56A, 0xB54B, 0x8528, 0x9509, 0xE5EE, 0xF5CF, 0xC5AC, 0xD58D,
    0x3653, 0x2672, 0x1611, 0x0630, 0x76D7, 0x66F6, 0x5695, 0x46B4,
    0xB75B, 0xA77A, 0x9719, 0x8738, 0xF7DF, 0xE7FE, 0xD79D, 0xC7BC,
    0x48C4, 0x58E5, 0x6886, 0x78A7, 0x0840, 0x1861, 0x2802, 0x3823,
    0xC9CC, 0xD9ED, 0xE98E, 0xF9AF, 0x8948, 0x9969, 0xA90A, 0xB92B,
    0x5AF5, 0x4AD4, 0x7AB7, 0x6A96, 0x1A71, 0x0A50, 0x3A33, 0x2A12,
    0xDBFD, 0xCBDC, 0xFBBF, 0xEB9E, 0x9B79, 0x8B58, 0xBB3B, 0xAB1A,
    0x6CA6, 0x7C87, 0x4CE4, 0x5CC5, 0x2C22, 0x3C03, 0x0C60, 0x1C41,
    0xEDAE, 0xFD8F, 0xCDEC, 0xDDCD, 0xAD2A, 0xBD0B, 0x8D68, 0x9D49,
    0x7E97, 0x6EB6, 0x5ED5, 0x4EF4, 0x3E13, 0x2E32, 0x1E51, 0x0E70,
    0xFF9F, 0xEFBE, 0xDFDD, 0xCFFC, 0xBF1B, 0xAF3A, 0x9F59, 0x8F78,
    0x9188, 0x81A9, 0xB1CA, 0xA1EB, 0xD10C, 0xC12D, 0xF14E, 0xE16F,
    0x1080, 0x00A1, 0x30C2, 0x20E3, 0x5004, 0x4025, 0x7046, 0x6067,
    0x83B9, 0x9398, 0xA3FB, 0xB3DA, 0xC33D, 0xD31C, 0xE37F, 0xF35E,
    0x02B1, 0x1290, 0x22F3, 0x32D2, 0x4235, 0x5214, 0x6277, 0x7256,
    0xB5EA, 0xA5CB, 0x95A8, 0x8589, 0xF56E, 0xE54F, 0xD52C, 0xC50D,
    0x34E2, 0x24C3, 0x14A0, 0x0481, 0x7466, 0x6447, 0x5424, 0x4405,
    0xA7DB, 0xB7FA, 0x8799, 0x97B8, 0xE75F, 0xF77E, 0xC71D, 0xD73C,
    0x26D3, 0x36F2, 0x0691, 0x16B0, 0x6657, 0x7676, 0x4615, 0x5634,
    0xD94C, 0xC96D, 0xF90E, 0xE92F, 0x99C8, 0x89E9, 0xB98A, 0xA9AB,
    0x5844, 0x4865, 0x7806, 0x6827, 0x18C0, 0x08E1, 0x3882, 0x28A3,
    0xCB7D, 0xDB5C, 0xEB3F, 0xFB1E, 0x8BF9, 0x9BD8, 0xABBB, 0xBB9A,
    0x4A75, 0x5A54, 0x6A37, 0x7A16, 0x0AF1, 0x1AD0, 0x2AB3, 0x3A92,
    0xFD2E, 0xED0F, 0xDD6C, 0xCD4D, 0xBDAA, 0xAD8B, 0x9DE8, 0x8DC9,
    0x7C26, 0x6C07, 0x5C64, 0x4C45, 0x3CA2, 0x2C83, 0x1CE0, 0x0CC1,
    0xEF1F, 0xFF3E, 0xCF5D, 0xDF7C, 0xAF9B, 0xBFBA, 0x8FD9, 0x9FF8,
    0x6E17, 0x7E36, 0x4E55, 0x5E74, 0x2E93, 0x3EB2, 0x0ED1, 0x1EF0,
};

uint16_t axiom_crc16(const uint8_t *data, size_t len) {
    uint16_t crc = 0xFFFFu;
    for (size_t i = 0; i < len; ++i) {
        crc = (uint16_t)((crc << 8) ^ axiom_crc16_table[((crc >> 8) ^ data[i]) & 0xFFu]);
    }
    return crc;
}

/* ===== axiom_ring.c ===== */
#include <assert.h>
#include <string.h>
#include <stdint.h>

#ifndef AXIOM_RING_BUFFER_POLICY_DROP
#define AXIOM_RING_BUFFER_POLICY_DROP 0
#endif

#ifndef AXIOM_RING_BUFFER_POLICY_OVERWRITE
#define AXIOM_RING_BUFFER_POLICY_OVERWRITE 1
#endif

#ifndef AXIOM_RING_BUFFER_POLICY
#define AXIOM_RING_BUFFER_POLICY AXIOM_RING_BUFFER_POLICY_DROP
#endif

/* Internal: store data buffer pointer in reserved field */
#define RING_BUF(ring) ((uint8_t *)(ring)->reserved)

void axiom_ring_write_chunk(axiom_ring_t *ring, const uint8_t *data, uint16_t len, uint16_t *crc) {
    uint32_t head = ring->head;
    uint32_t mask = ring->mask;
    uint8_t *buf = RING_BUF(ring);
    
    for (uint16_t i = 0; i < len; ++i) {
        uint8_t b = data[i];
        buf[head & mask] = b;
        head++;
        if (crc) {
            *crc = axiom_crc16_update(*crc, b);
        }
    }
    ring->head = head;
}

void axiom_ring_init(axiom_ring_t *ring, uint8_t *buf, uint32_t size) {
    /* 验证 size 是 2 的幂，否则 mask 计算会出错 */
    assert((size & (size - 1)) == 0 && "Ring buffer size must be power of 2");

    ring->head = 0;
    ring->tail = 0;
    ring->capacity = size;
    ring->mask = size - 1;
    ring->reserved = (uintptr_t)buf;
}

bool axiom_ring_write(axiom_ring_t *ring, const uint8_t *data, uint16_t len) {
    if (len == 0 || len > ring->capacity) {
        return false;
    }

    axiom_port_critical_enter();

    uint32_t head = ring->head;
    uint32_t tail = ring->tail;
    uint32_t cap  = ring->capacity;
    uint32_t mask = ring->mask;
    uint32_t used = head - tail;
    uint8_t *buf  = RING_BUF(ring);

    if (used + len > cap) {
#if AXIOM_RING_BUFFER_POLICY == AXIOM_RING_BUFFER_POLICY_DROP
        axiom_port_critical_exit();
        return false;
#else
        /* OVERWRITE: blind advancement of tail to maintain O(1).
         * Decoder is responsible for handling partially overwritten frames.
         */
        tail = (head + len) - cap;
#endif
    }

    for (uint16_t i = 0; i < len; ++i) {
        buf[(head + i) & mask] = data[i];
    }
    ring->head = head + len;
    ring->tail = tail;

    axiom_port_critical_exit();
    return true;
}

uint16_t axiom_ring_read(axiom_ring_t *ring, uint8_t *out, uint16_t max_len) {
    if (!out || max_len == 0) return 0;

    axiom_port_critical_enter();

    uint32_t head = ring->head;
    uint32_t tail = ring->tail;
    uint32_t mask = ring->mask;
    uint32_t avail = head - tail;
    uint16_t n = (avail < max_len) ? (uint16_t)avail : max_len;
    uint8_t *buf = RING_BUF(ring);

    for (uint16_t i = 0; i < n; ++i) {
        out[i] = buf[(tail + i) & mask];
    }
    ring->tail = tail + n;

    axiom_port_critical_exit();
    return n;
}

uint16_t axiom_ring_peek(const axiom_ring_t *ring, uint8_t *out, uint16_t max_len) {
    if (!out || max_len == 0) return 0;

    axiom_port_critical_enter();

    uint32_t head = ring->head;
    uint32_t tail = ring->tail;
    uint32_t mask = ring->mask;
    uint32_t avail = head - tail;
    uint16_t n = (avail < max_len) ? (uint16_t)avail : max_len;
    const uint8_t *buf = (const uint8_t *)ring->reserved;

    for (uint16_t i = 0; i < n; ++i) {
        out[i] = buf[(tail + i) & mask];
    }

    axiom_port_critical_exit();
    return n;
}

void axiom_ring_consume(axiom_ring_t *ring, uint16_t n) {
    axiom_port_critical_enter();
    ring->tail += n;
    axiom_port_critical_exit();
}

void axiom_ring_reset(axiom_ring_t *ring) {
    axiom_port_critical_enter();
    ring->head = 0;
    ring->tail = 0;
    axiom_port_critical_exit();
}

/* ===== axiom_timestamp.c ===== */

void axiom_timestamp_init(axiom_timestamp_ctx_t *ctx) {
    ctx->last_raw = 0;
    ctx->baseline = 0;
}

uint8_t axiom_timestamp_encode(axiom_timestamp_ctx_t *ctx, uint8_t *out) {
    uint32_t raw = axiom_port_timestamp();
    uint32_t delta = raw - ctx->last_raw;
    ctx->last_raw = raw;

    /* Variable-length encoding: smaller deltas use fewer bytes */
    if (delta <= 0x7Fu) {
        out[0] = (uint8_t)(delta & 0x7Fu);
        return 1;
    } else if (delta <= 0x3FFFu) {
        out[0] = (uint8_t)(0x80u | ((delta >> 8) & 0x3Fu));
        out[1] = (uint8_t)(delta & 0xFFu);
        return 2;
    } else if (delta <= 0x1FFFFFu) {
        out[0] = (uint8_t)(0xC0u | ((delta >> 16) & 0x1Fu));
        out[1] = (uint8_t)((delta >> 8) & 0xFFu);
        out[2] = (uint8_t)(delta & 0xFFu);
        return 3;
    } else {
        /* 使用 0xFE 标记大 delta，0xFF 可以正常出现在数据中 */
        out[0] = 0xFEu;
        out[1] = (uint8_t)(delta & 0xFFu);
        out[2] = (uint8_t)((delta >> 8) & 0xFFu);
        out[3] = (uint8_t)((delta >> 16) & 0xFFu);
        out[4] = (uint8_t)((delta >> 24) & 0xFFu);
        return 5;
    }
}

/* ===== axiom_filter.c ===== */

void axiom_filter_init(axiom_filter_t *filter) {
    filter->level_mask  = 0xFFFFFFFFu;
    filter->module_mask = 0xFFFFFFFFu;
    filter->drop_count  = 0;
    filter->drop_module = 0;
    filter->drop_event  = 0;
    filter->drop_pending = false;
}

bool axiom_filter_check(axiom_filter_t *filter, axiom_level_t level, uint8_t module_id) {
    if (level >= AXIOM_LEVEL_MAX) return false;
    if ((filter->level_mask & (1u << (uint32_t)level)) == 0) return false;
    /* 32-bit mask limits per-module filtering to module_id 0..(AXIOM_MODULE_MAX-1).
     * Modules with id >= AXIOM_MODULE_MAX always pass the filter (no masking applied). */
    if (module_id < AXIOM_MODULE_MAX && (filter->module_mask & (1u << (uint32_t)module_id)) == 0) return false;
    return true;
}

void axiom_filter_drop(axiom_filter_t *filter, uint8_t module_id, uint16_t event_id) {
    filter->drop_count++;
    filter->drop_module = module_id;
    filter->drop_event  = event_id;
    filter->drop_pending = true;
}

bool axiom_filter_drop_summary_ready(axiom_filter_t *filter) {
    return filter->drop_pending;
}

uint32_t axiom_filter_drop_count_get_and_clear(axiom_filter_t *filter) {
    uint32_t count = filter->drop_count;
    filter->drop_count = 0;
    filter->drop_pending = false;
    filter->drop_module = 0;
    filter->drop_event  = 0;
    return count;
}

/* ===== axiom_event.c ===== */
#include <string.h>

#ifndef AXIOM_RING_BUFFER_SIZE
#define AXIOM_RING_BUFFER_SIZE 4096u
#endif

static uint8_t s_ring_buf[AXIOM_RING_BUFFER_SIZE];
static axiom_ring_t s_ring;
static uint16_t s_seq;
static axiom_filter_t s_filter;
static axiom_timestamp_ctx_t s_ts_ctx;

void axiom_init(void) {
    axiom_ring_init(&s_ring, s_ring_buf, AXIOM_RING_BUFFER_SIZE);
    s_seq = 0;
    axiom_filter_init(&s_filter);
    axiom_timestamp_init(&s_ts_ctx);
}

void axiom_flush(void) {
    uint8_t frame[AXIOM_MAX_FRAME_LEN];
    uint16_t n;
    while ((n = axiom_ring_peek(&s_ring, frame, sizeof(frame))) > 0) {
        /* Frame structure: Header(8B) + Timestamp(1-5B) + PayloadLen(1B) + Payload(N) + CRC(2B) */
        /* Minimum frame: header(8) + timestamp(1) + payload_len(1) + crc(2) = 12 */
        if (n < 12) break;
        /* Decode variable-length timestamp to find payload_len offset */
        uint8_t ts_len = axiom_timestamp_decode_len(frame[8]);
        /* Determine actual frame length */
        uint16_t payload_len = frame[8 + ts_len];
        uint16_t frame_len = (uint16_t)(8u + ts_len + 1u + payload_len + 2u);
        if (n < frame_len) break;
        /* Data already copied by peek — just advance the tail pointer */
        axiom_ring_consume(&s_ring, frame_len);
        axiom_backend_dispatch(frame, frame_len);
    }
}

void axiom_write(axiom_level_t level, uint8_t module_id, uint16_t event_id,
                 const uint8_t *payload, uint8_t payload_len) {
    if (level >= AXIOM_LEVEL_MAX) return;

    if (!axiom_filter_check(&s_filter, level, module_id)) {
        axiom_filter_drop(&s_filter, module_id, event_id);
        return;
    }

    if (level == AXIOM_LEVEL_FAULT) {
        axiom_port_fault_hook(module_id, event_id, payload, payload_len);
    }

    axiom_port_critical_enter();

    /* Encode timestamp inside critical section — s_ts_ctx.last_raw
     * must not be corrupted by a pre-empting ISR calling axiom_write() */
    uint8_t ts_buf[5];
    uint8_t ts_len = axiom_timestamp_encode(&s_ts_ctx, ts_buf);
    uint16_t total_len = (uint16_t)(8u + ts_len + 1u + payload_len + 2u);

    /* Capacity check & Policy enforcement */
    uint32_t head = s_ring.head;
    uint32_t tail = s_ring.tail;
    uint32_t cap  = s_ring.capacity;
    uint32_t used = head - tail;

    if (used + total_len > cap) {
#if AXIOM_RING_BUFFER_POLICY == AXIOM_RING_BUFFER_POLICY_DROP
        axiom_port_critical_exit();
        return;
#else
        /* OVERWRITE: blind advancement of tail */
        s_ring.tail = (head + total_len) - cap;
#endif
    }

    uint16_t crc = 0xFFFFu;
    uint8_t header[8];
    header[0] = 0xA5;
    header[1] = AXIOM_WIRE_VERSION;
    header[2] = (uint8_t)level;
    header[3] = module_id;
    header[4] = (uint8_t)(event_id & 0xFFu);
    header[5] = (uint8_t)(event_id >> 8);
    header[6] = (uint8_t)(s_seq & 0xFFu);
    header[7] = (uint8_t)(s_seq >> 8);
    s_seq++;

    /* Phase 1: Header */
    axiom_ring_write_chunk(&s_ring, header, 8, &crc);
    /* Phase 2: Timestamp */
    axiom_ring_write_chunk(&s_ring, ts_buf, ts_len, &crc);
    /* Phase 3: Payload Length */
    axiom_ring_write_chunk(&s_ring, &payload_len, 1, &crc);
    /* Phase 4: Payload */
    if (payload_len > 0 && payload) {
        axiom_ring_write_chunk(&s_ring, payload, payload_len, &crc);
    }
    /* Phase 5: Final CRC */
    uint8_t crc_buf[2];
    crc_buf[0] = (uint8_t)(crc & 0xFFu);
    crc_buf[1] = (uint8_t)(crc >> 8);
    axiom_ring_write_chunk(&s_ring, crc_buf, 2, NULL);

    /* Snapshot drop statistics atomically before leaving the critical section.
     * Prevents a pre-empting ISR from corrupting drop_count mid-read. */
    const bool     has_drop    = s_filter.drop_pending;
    uint32_t       cached_lost = 0;
    uint8_t        cached_mod  = 0;
    uint16_t       cached_evt  = 0;
    if (has_drop) {
        cached_lost = s_filter.drop_count;
        cached_mod  = s_filter.drop_module;
        cached_evt  = s_filter.drop_event;
        /* Clear atomically — next drop will start fresh */
        s_filter.drop_count   = 0;
        s_filter.drop_pending = false;
        s_filter.drop_module  = 0;
        s_filter.drop_event   = 0;
    }

    axiom_port_critical_exit();

    /* Emit DROP_SUMMARY outside critical section.
     * Recursive axiom_write() is safe: it has its own critical section.
     * Using cached_* locals avoids touching s_filter after CS exit. */
    if (has_drop) {
        uint8_t summary[10];
        uint8_t sp = 0;
        summary[sp++] = AXIOM_TYPE_U32;
        summary[sp++] = (uint8_t)(cached_lost & 0xFFu);
        summary[sp++] = (uint8_t)((cached_lost >> 8) & 0xFFu);
        summary[sp++] = (uint8_t)((cached_lost >> 16) & 0xFFu);
        summary[sp++] = (uint8_t)(cached_lost >> 24);
        summary[sp++] = AXIOM_TYPE_U8;
        summary[sp++] = cached_mod;
        summary[sp++] = AXIOM_TYPE_U16;
        summary[sp++] = (uint8_t)(cached_evt & 0xFFu);
        summary[sp++] = (uint8_t)(cached_evt >> 8);
        axiom_write(AXIOM_LEVEL_WARN, 0x00, 0x0001, summary, sp);
    }

    /* NOTE: axiom_filter_drop() above is called outside critical section.
     * On 32-bit MCUs, drop_count++ is typically atomic (single LDR+STR),
     * but under extreme contention a count increment may be lost.
     * This is acceptable for statistics — no data corruption occurs. */
}

/* ---------------------------------------------------------------------------
 * Runtime filter control API — operates on the global s_filter instance
 * --------------------------------------------------------------------------- */
void axiom_level_mask_set(uint32_t mask) {
    s_filter.level_mask = mask;
}

uint32_t axiom_level_mask_get(void) {
    return s_filter.level_mask;
}

void axiom_module_mask_set(uint32_t mask) {
    s_filter.module_mask = mask;
}

uint32_t axiom_module_mask_get(void) {
    return s_filter.module_mask;
}
/* ===== axiom_backend.c ===== */

static const axiom_backend_t *s_backends[AXIOM_BACKEND_MAX];
static uint8_t s_backend_count = 0;

int axiom_backend_register(const axiom_backend_t *backend) {
    if (!backend || !backend->write) {
        return -1;
    }
    if (s_backend_count >= AXIOM_BACKEND_MAX) {
        return -2;
    }
    /* Backward compatibility: old backends may be zero-initialized with size==0.
     * Treat size==0 as legacy layout (v1 without the size field).
     * size > 0 but < current sizeof means a newer library compiled against
     * an older struct — reject to prevent reading garbage. */
    if (backend->size != 0 && backend->size < sizeof(axiom_backend_t)) {
        return -3; /* struct too small — recompile the backend */
    }
    s_backends[s_backend_count++] = backend;
    return 0;
}

void axiom_backend_dispatch(const uint8_t *frame, uint16_t len) {
    for (uint8_t i = 0; i < s_backend_count; ++i) {
        const axiom_backend_t *be = s_backends[i];
        if (be->ready && !be->ready(be->ctx)) {
            if (be->on_drop) {
                be->on_drop(1, be->ctx);
            }
            continue;
        }
        int ret = be->write(frame, len, be->ctx);
        if (ret < 0 && be->on_drop) {
            be->on_drop(1, be->ctx);
        }
    }
}

void axiom_backend_flush_all(void) {
    for (uint8_t i = 0; i < s_backend_count; ++i) {
        const axiom_backend_t *be = s_backends[i];
        if (be->flush) {
            (void)be->flush(be->ctx);
        }
    }
}

void axiom_backend_panic_write(const uint8_t *frame, uint16_t len) {
    for (uint8_t i = 0; i < s_backend_count; ++i) {
        const axiom_backend_t *be = s_backends[i];
        if (be->panic_write) {
            (void)be->panic_write(frame, len, be->ctx);
        } else if (be->write) {
            (void)be->write(frame, len, be->ctx);
        }
    }
}

#ifdef __cplusplus
}
#endif

#endif /* AXIOMTRACE_H */
