/* ============================================================================
 * AxiomTrace Single-File Amalgamated Library
 * Auto-generated by tool/scripts/amalgamate.py
 * ============================================================================ */

#ifndef AXIOMTRACE_H
#define AXIOMTRACE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ===== axiom_static_assert.h ===== */
#ifndef AXIOM_STATIC_ASSERT_H
#define AXIOM_STATIC_ASSERT_H

/* ---------------------------------------------------------------------------
 * Compile-time assertions (C11 _Static_assert wrapper)
 * --------------------------------------------------------------------------- */

#define AXIOM_STATIC_ASSERT(expr, msg) _Static_assert((expr), msg)

#define AXIOM_CHECK_SIZE(type, expected) \
    AXIOM_STATIC_ASSERT(sizeof(type) == (expected), #type " size mismatch")

#define AXIOM_CHECK_ALIGN(type, align) \
    AXIOM_STATIC_ASSERT(_Alignof(type) == (align), #type " align mismatch")

#define AXIOM_CHECK_FIELD_OFFSET(type, field, expected) \
    AXIOM_STATIC_ASSERT(__builtin_offsetof(type, field) == (expected), #type "." #field " offset mismatch")

#define AXIOM_CHECK_RANGE(val, min, max) \
    AXIOM_STATIC_ASSERT((val) >= (min) && (val) <= (max), #val " out of range")

#define AXIOM_CHECK_POWER_OF_TWO(val) \
    AXIOM_STATIC_ASSERT(((val) != 0) && (((val) & ((val) - 1)) == 0), #val " must be power of two")

#define AXIOM_CHECK_ARRAY_SIZE(arr, expected) \
    AXIOM_STATIC_ASSERT((sizeof(arr) / sizeof((arr)[0])) == (expected), #arr " size mismatch")

#endif /* AXIOM_STATIC_ASSERT_H */

/* ===== axiom_config.h ===== */
#ifndef AXIOM_CONFIG_H
#define AXIOM_CONFIG_H

#include <stdint.h>

/* ---------------------------------------------------------------------------
 * Library Version (SemVer 2.0.0)
 * Bump on release. Checked at compile-time by downstream consumers.
 * --------------------------------------------------------------------------- */
#define AXIOMTRACE_VERSION_MAJOR 0u
#define AXIOMTRACE_VERSION_MINOR 7u
#define AXIOMTRACE_VERSION_PATCH 0u

/* Compile-time version check: AXIOMTRACE_VERSION_CHECK(0,7,0) */
#define AXIOMTRACE_VERSION_CHECK(ma, mi, pa) \
    ((AXIOMTRACE_VERSION_MAJOR > (ma)) ||    \
     (AXIOMTRACE_VERSION_MAJOR == (ma) && AXIOMTRACE_VERSION_MINOR > (mi)) || \
     (AXIOMTRACE_VERSION_MAJOR == (ma) && AXIOMTRACE_VERSION_MINOR == (mi) && \
      AXIOMTRACE_VERSION_PATCH >= (pa)))

/* ---------------------------------------------------------------------------
 * Compiler Helpers
 * --------------------------------------------------------------------------- */

/* Mark a symbol as deprecated with a migration hint.
 * Example: AXIOM_DEPRECATED("use axiom_new_api() instead") */
#if defined(__GNUC__) || defined(__clang__)
#define AXIOM_DEPRECATED(msg) __attribute__((deprecated(msg)))
#elif defined(_MSC_VER)
#define AXIOM_DEPRECATED(msg) __declspec(deprecated(msg))
#elif defined(__IAR_SYSTEMS_ICC__)
#define AXIOM_DEPRECATED(msg) _Pragma("message=\"" msg "\"")
#else
#define AXIOM_DEPRECATED(msg)
#endif

/* ---------------------------------------------------------------------------
 * Debug Switch (NEW)
 * Enables runtime assertions and diagnostic hooks when set to 1.
 * Cost: ~50 bytes ROM for assert handlers. Disable in production.
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_DEBUG
#define AXIOM_DEBUG 0
#endif

/* Source-location metadata modes. Metadata is a tagged suffix in the wire v2
 * packed payload; the fixed 8-byte frame header is unchanged. */
#define AXIOM_CFG_LOCATION_MODE_NONE    0
#define AXIOM_CFG_LOCATION_MODE_HASH    1
#define AXIOM_CFG_LOCATION_MODE_FILE_ID 2

/* ---------------------------------------------------------------------------
 * Resource Presets
 * A single knob for common MCU classes. Every value remains individually
 * overridable by defining the specific macro before including axiomtrace.h or
 * by passing a compile definition from the build system.
 * --------------------------------------------------------------------------- */
#define AXIOM_PROFILE_DEV    0
#define AXIOM_PROFILE_FIELD  1
#define AXIOM_PROFILE_PROD   2

#define AXIOM_PRESET_CUSTOM 0
#define AXIOM_PRESET_TINY   1
#define AXIOM_PRESET_PROD   2
#define AXIOM_PRESET_FIELD  3
#define AXIOM_PRESET_DEV    4

#ifndef AXIOM_PRESET
#define AXIOM_PRESET AXIOM_PRESET_DEV
#endif

#if (AXIOM_PRESET < AXIOM_PRESET_CUSTOM) || (AXIOM_PRESET > AXIOM_PRESET_DEV)
#error "Invalid AXIOM_PRESET. Use CUSTOM, TINY, PROD, FIELD, or DEV."
#endif

#if AXIOM_PRESET == AXIOM_PRESET_TINY
    #ifndef AXIOM_PROFILE
    #define AXIOM_PROFILE AXIOM_PROFILE_PROD
    #endif
    #ifndef AXIOM_RING_BUFFER_SIZE
    #define AXIOM_RING_BUFFER_SIZE 256u
    #endif
    #ifndef AXIOM_MAX_PAYLOAD_LEN
    #define AXIOM_MAX_PAYLOAD_LEN 32u
    #endif
    #ifndef AXIOM_MODULE_MAX
    #define AXIOM_MODULE_MAX 16u
    #endif
    #ifndef AXIOM_CFG_LOCATION_MODE
    #define AXIOM_CFG_LOCATION_MODE AXIOM_CFG_LOCATION_MODE_NONE
    #endif
    #ifndef AXIOM_CFG_TIME_SYNC_ENABLED
    #define AXIOM_CFG_TIME_SYNC_ENABLED 0
    #endif
    #ifndef AXIOM_SHORT_CS
    #define AXIOM_SHORT_CS 0
    #endif
    #ifndef AXIOM_BACKEND_DEGRADATION
    #define AXIOM_BACKEND_DEGRADATION 0
    #endif
    #ifndef AXIOM_CAPSULE_ENABLED
    #define AXIOM_CAPSULE_ENABLED 0
    #endif
#elif AXIOM_PRESET == AXIOM_PRESET_PROD
    #ifndef AXIOM_PROFILE
    #define AXIOM_PROFILE AXIOM_PROFILE_PROD
    #endif
    #ifndef AXIOM_RING_BUFFER_SIZE
    #define AXIOM_RING_BUFFER_SIZE 1024u
    #endif
    #ifndef AXIOM_MAX_PAYLOAD_LEN
    #define AXIOM_MAX_PAYLOAD_LEN 64u
    #endif
    #ifndef AXIOM_CFG_LOCATION_MODE
    #define AXIOM_CFG_LOCATION_MODE AXIOM_CFG_LOCATION_MODE_NONE
    #endif
    #ifndef AXIOM_CFG_TIME_SYNC_ENABLED
    #define AXIOM_CFG_TIME_SYNC_ENABLED 0
    #endif
    #ifndef AXIOM_CAPSULE_ENABLED
    #define AXIOM_CAPSULE_ENABLED 0
    #endif
#elif AXIOM_PRESET == AXIOM_PRESET_FIELD
    #ifndef AXIOM_PROFILE
    #define AXIOM_PROFILE AXIOM_PROFILE_FIELD
    #endif
    #ifndef AXIOM_RING_BUFFER_SIZE
    #define AXIOM_RING_BUFFER_SIZE 2048u
    #endif
    #ifndef AXIOM_MAX_PAYLOAD_LEN
    #define AXIOM_MAX_PAYLOAD_LEN 96u
    #endif
    #ifndef AXIOM_CAPSULE_PRE_EVENTS
    #define AXIOM_CAPSULE_PRE_EVENTS 16u
    #endif
    #ifndef AXIOM_CAPSULE_POST_EVENTS
    #define AXIOM_CAPSULE_POST_EVENTS 8u
    #endif
    #ifndef AXIOM_CAPSULE_RING_SIZE
    #define AXIOM_CAPSULE_RING_SIZE 2048u
    #endif
#elif AXIOM_PRESET == AXIOM_PRESET_DEV
    #ifndef AXIOM_PROFILE
    #define AXIOM_PROFILE AXIOM_PROFILE_DEV
    #endif
#endif

/* ---------------------------------------------------------------------------
 * Core Configuration
 * --------------------------------------------------------------------------- */

/* Main ring buffer size. MUST be a power of two. */
#ifndef AXIOM_RING_BUFFER_SIZE
#define AXIOM_RING_BUFFER_SIZE 4096u
#endif

/* DROP: Discard new events when full. 
 * OVERWRITE: Overwrite oldest events when full (maintains O(1)). */
#define AXIOM_RING_BUFFER_POLICY_DROP      0
#define AXIOM_RING_BUFFER_POLICY_OVERWRITE 1

#ifndef AXIOM_RING_BUFFER_POLICY
#define AXIOM_RING_BUFFER_POLICY AXIOM_RING_BUFFER_POLICY_DROP
#endif

/* Maximum payload size per event in bytes. */
#ifndef AXIOM_MAX_PAYLOAD_LEN
#define AXIOM_MAX_PAYLOAD_LEN 128u
#endif

/* Maximum number of unique module IDs (0 .. AXIOM_MODULE_MAX-1).
 * Determines the width of the module filter bitmask. */
#ifndef AXIOM_MODULE_MAX
#define AXIOM_MODULE_MAX 32u
#endif

/* ---------------------------------------------------------------------------
 * Observability Extensions
 * --------------------------------------------------------------------------- */

/* Compatibility switch retained for existing integrations. New code should
 * select AXIOM_CFG_LOCATION_MODE explicitly. */
#ifndef AXIOM_CFG_USE_LOCATION
#define AXIOM_CFG_USE_LOCATION 0
#endif

#ifndef AXIOM_CFG_LOCATION_MODE
#if AXIOM_CFG_USE_LOCATION
#define AXIOM_CFG_LOCATION_MODE AXIOM_CFG_LOCATION_MODE_HASH
#else
#define AXIOM_CFG_LOCATION_MODE AXIOM_CFG_LOCATION_MODE_NONE
#endif
#endif

/* Include a function hash only in HASH mode. Production FILE_ID mode restores
 * function information on the host from retained build artifacts. */
#ifndef AXIOM_CFG_LOCATION_FUNCTION
#define AXIOM_CFG_LOCATION_FUNCTION 0
#endif

/* FILE_ID mode callers may override this per translation unit. */
#ifndef AXIOM_SOURCE_FILE_ID
#define AXIOM_SOURCE_FILE_ID 0u
#endif

/* If enabled, the core will periodically (or manually) emit sync events
 * to map local counters to host-provided Unix time. */
#ifndef AXIOM_CFG_TIME_SYNC_ENABLED
#define AXIOM_CFG_TIME_SYNC_ENABLED 1
#endif

/* ---------------------------------------------------------------------------
 * Encode Overflow Detection (optimization #10)
 * When enabled, axiom_enc_xxx() silently skips writes that would exceed
 * AXIOM_MAX_PAYLOAD_LEN and sets axiom_encode_overflow=true.
 * Cost: 1 byte RAM + 1 branch per enc call (mostly predicted-not-taken).
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_ENCODE_OVERFLOW_DETECTION
#define AXIOM_ENCODE_OVERFLOW_DETECTION 1
#endif

/* ---------------------------------------------------------------------------
 * Short Critical Section (optimization #1)
 * When enabled (default), axiom_write() pre-encodes the entire frame into
 * a stack buffer OUTSIDE the critical section, then performs a single
 * ring_write() INSIDE the critical section. Minimizes interrupt latency.
 * Cost: +AXIOM_MAX_FRAME_LEN bytes of stack per axiom_write() call.
 * Set to 0 on extremely RAM-constrained MCUs to save ~255B stack.
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_SHORT_CS
#define AXIOM_SHORT_CS 1
#endif

/* ---------------------------------------------------------------------------
 * Runtime Self-Test (NEW)
 * When enabled, axiom_selftest() validates CRC, ring buffer, and encoder
 * at boot time. Returns true if all checks pass.
 * Cost: ~200B stack + ~2KB ROM for test vectors. Call axiom_selftest()
 * once in main() before first axiom_write().
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_SELFTEST
#define AXIOM_SELFTEST 0
#endif

/* ---------------------------------------------------------------------------
 * Backend Degradation & Recovery (NEW)
 * When enabled, a backend that fails AXIOM_BACKEND_FAIL_THRESHOLD
 * consecutive writes is soft-disabled for AXIOM_BACKEND_RECOVERY_US
 * microseconds, then auto-recovered. Prevents a broken transport
 * (e.g., unplugged UART) from stalling all backends.
 * Panic path always bypasses degradation.
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_BACKEND_DEGRADATION
#define AXIOM_BACKEND_DEGRADATION 1
#endif

#if AXIOM_BACKEND_DEGRADATION
    #ifndef AXIOM_BACKEND_FAIL_THRESHOLD
    #define AXIOM_BACKEND_FAIL_THRESHOLD 5
    #endif
    #ifndef AXIOM_BACKEND_RECOVERY_US
    #define AXIOM_BACKEND_RECOVERY_US 1000000u  /* 1 second */
    #endif
#endif

/* ---------------------------------------------------------------------------
 * Fault Capsule
 * Captures pre/post fault Event Records into RAM and commits a CRC-protected
 * capsule image to the port flash backend only when axiom_capsule_commit()
 * is called from a non-hot path.
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_CAPSULE_ENABLED
#define AXIOM_CAPSULE_ENABLED 1
#endif

#ifndef AXIOM_CAPSULE_PRE_EVENTS
#define AXIOM_CAPSULE_PRE_EVENTS 32u
#endif

#ifndef AXIOM_CAPSULE_POST_EVENTS
#define AXIOM_CAPSULE_POST_EVENTS 16u
#endif

#ifndef AXIOM_CAPSULE_RING_SIZE
#define AXIOM_CAPSULE_RING_SIZE 4096u
#endif

#ifndef AXIOM_CAPSULE_MAX_SNAPSHOT_LEN
#define AXIOM_CAPSULE_MAX_SNAPSHOT_LEN 64u
#endif

#ifndef AXIOM_CAPSULE_FLASH_BASE
#define AXIOM_CAPSULE_FLASH_BASE 0u
#endif

#ifndef AXIOM_CAPSULE_FLASH_SIZE
#define AXIOM_CAPSULE_FLASH_SIZE 8192u
#endif

#ifndef AXIOM_CAPSULE_FIRMWARE_HASH
#define AXIOM_CAPSULE_FIRMWARE_HASH 0u
#endif

#ifndef AXIOM_CAPSULE_SNAPSHOT_ID
#define AXIOM_CAPSULE_SNAPSHOT_ID 0u
#endif

#define AXIOM_CAPSULE_MAX_IMAGE_SIZE \
    (21u + AXIOM_CAPSULE_MAX_SNAPSHOT_LEN + AXIOM_CAPSULE_RING_SIZE + 4u)

#endif /* AXIOM_CONFIG_H */

/* ===== axiom_port.h ===== */
#ifndef AXIOM_PORT_H
#define AXIOM_PORT_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Port layer — override by providing strong-symbol implementations.
 * Default weak implementations are in axiom_port_generic.c.
 * --------------------------------------------------------------------------- */

/* Monotonic timestamp in microseconds (wraps naturally) */
extern uint32_t axiom_port_timestamp(void);

#if defined(AXIOM_HOST_TESTING)
/* Mutable generic-port time source used only by host regression tests. */
extern uint32_t g_axiom_port_simulated_time;
#endif

/* Critical section: must be nestable or simply disable/enable IRQs */
extern void axiom_port_critical_enter(void);
extern void axiom_port_critical_exit(void);

/* String output for development logs (AX_LOG). May be UART/RTT/stdout. */
extern void axiom_port_string_out(const char *str);

/* Fault hook: called on AX_FAULT events. Override to customize behavior. */
extern void axiom_port_fault_hook(uint8_t module_id, uint16_t event_id,
                                   const uint8_t *payload, uint8_t payload_len);

/* Reset reason for fault capsule headers. Returns 0 when unavailable. */
extern uint8_t axiom_port_reset_reason(void);

/* Register snapshot for fault capsule. Returns bytes written. */
extern uint8_t axiom_port_fault_snapshot(uint8_t *buf, uint8_t max_len);

/* Flash operations for capsule backend (non-ISR only) */
extern int axiom_port_flash_erase(uint32_t addr, uint32_t len);
extern int axiom_port_flash_write(uint32_t addr, const uint8_t *data, uint32_t len);
extern int axiom_port_flash_read(uint32_t addr, uint8_t *out, uint32_t len);

#if defined(AXIOM_HOST_TESTING)
#ifndef AXIOM_HOST_FLASH_SIZE
#define AXIOM_HOST_FLASH_SIZE 65536u
#endif
extern uint8_t g_axiom_port_reset_reason;
extern uint8_t g_axiom_port_fault_snapshot_data[64];
extern uint8_t g_axiom_port_fault_snapshot_len;
extern uint8_t g_axiom_port_flash_storage[AXIOM_HOST_FLASH_SIZE];
extern uint32_t g_axiom_port_flash_erase_calls;
extern uint32_t g_axiom_port_flash_write_calls;
extern uint32_t g_axiom_port_flash_read_calls;
extern uint32_t g_axiom_port_flash_write_limit;
extern int g_axiom_port_flash_fail_erase;
extern int g_axiom_port_flash_fail_write;
extern int g_axiom_port_flash_fail_read;
void axiom_port_host_flash_reset(void);
#endif

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_PORT_H */

/* ===== axiom_event.h ===== */
#ifndef AXIOM_EVENT_H
#define AXIOM_EVENT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Log levels
 * --------------------------------------------------------------------------- */
typedef enum {
    AXIOM_LEVEL_DEBUG = 0,
    AXIOM_LEVEL_INFO  = 1,
    AXIOM_LEVEL_WARN  = 2,
    AXIOM_LEVEL_ERROR = 3,
    AXIOM_LEVEL_FAULT = 4,
    AXIOM_LEVEL_MAX   = 5
} axiom_level_t;

/* ---------------------------------------------------------------------------
 * Sync byte (frame delimiter)
 * --------------------------------------------------------------------------- */
#define AXIOM_SYNC_BYTE 0xA5u

/* ---------------------------------------------------------------------------
 * Event header: exactly 8 bytes, packed, little-endian on wire
 * --------------------------------------------------------------------------- */
typedef struct __attribute__((packed)) {
    uint8_t  sync;       /* AXIOM_SYNC_BYTE = 0xA5 */
    uint8_t  version;    /* major << 4 | minor */
    uint8_t  level;      /* lower nibble: level, upper nibble: reserved (0) */
    uint8_t  module_id;
    uint16_t event_id;   /* little-endian */
    uint16_t seq;        /* little-endian */
} axiom_event_header_t;

AXIOM_CHECK_SIZE(axiom_event_header_t, 8);
AXIOM_CHECK_ALIGN(axiom_event_header_t, 1);

/* ---------------------------------------------------------------------------
 * Wire v1 payload tags and wire v2 metadata suffix tags.
 *
 * Normal event arguments are schema-driven packed values in wire v2. The
 * numeric constants remain public for legacy v1 decoding, the reserved v2
 * AX_PROBE system payload, and metadata suffix fields that remain tagged.
 * --------------------------------------------------------------------------- */
typedef enum {
    AXIOM_TYPE_BOOL      = 0x00,
    AXIOM_TYPE_U8        = 0x01,
    AXIOM_TYPE_I8        = 0x02,
    AXIOM_TYPE_U16       = 0x03,
    AXIOM_TYPE_I16       = 0x04,
    AXIOM_TYPE_U32       = 0x05,
    AXIOM_TYPE_I32       = 0x06,
    AXIOM_TYPE_F32       = 0x07,
    AXIOM_TYPE_TIMESTAMP = 0x08,
    AXIOM_TYPE_BYTES     = 0x09,
    AXIOM_TYPE_META_LOCATION = 0x0A,
    AXIOM_TYPE_META_IDENTITY = 0x0B
    /* Reserved: 0x0C - 0x7F, User-defined: 0x80 - 0xFF */
} axiom_type_t;

/* Backward-compatible macros: allow existing code (including _Generic,
 * sizeof checks, and preprocessor usage) to keep working. */
#define AXIOM_TYPE_BOOL      0x00u
#define AXIOM_TYPE_U8        0x01u
#define AXIOM_TYPE_I8        0x02u
#define AXIOM_TYPE_U16       0x03u
#define AXIOM_TYPE_I16       0x04u
#define AXIOM_TYPE_U32       0x05u
#define AXIOM_TYPE_I32       0x06u
#define AXIOM_TYPE_F32       0x07u
#define AXIOM_TYPE_TIMESTAMP 0x08u
#define AXIOM_TYPE_BYTES     0x09u
#define AXIOM_TYPE_META_LOCATION 0x0Au
#define AXIOM_TYPE_META_IDENTITY 0x0Bu

/* ---------------------------------------------------------------------------
 * Wire format version v2.0.
 *
 * v2 changes normal argument encoding from typed fields to dictionary-driven
 * packed values. This is intentionally a major-version transition.
 * --------------------------------------------------------------------------- */
#define AXIOM_WIRE_VERSION_MAJOR 2u
#define AXIOM_WIRE_VERSION_MINOR 0u
#define AXIOM_WIRE_VERSION ((uint8_t)((AXIOM_WIRE_VERSION_MAJOR << 4u) | AXIOM_WIRE_VERSION_MINOR))

/* ---------------------------------------------------------------------------
 * Frame layout constants
 * --------------------------------------------------------------------------- */
#define AXIOM_HEADER_LEN          8u  /* 8-byte fixed header */
#define AXIOM_MAX_TIMESTAMP_LEN   5u  /* 0xFE + 4-byte full delta */
#define AXIOM_CRC_LEN             2u  /* CRC-16 trailer */

/* Total max frame: header + timestamp + payload length + payload + CRC. */
#define AXIOM_MAX_FRAME_LEN \
    (AXIOM_HEADER_LEN + AXIOM_MAX_TIMESTAMP_LEN + 1u + AXIOM_MAX_PAYLOAD_LEN + AXIOM_CRC_LEN)

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_EVENT_H */

/* ===== axiom_encode.h ===== */
#ifndef AXIOM_ENCODE_H
#define AXIOM_ENCODE_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* ---------------------------------------------------------------------------
 * Overflow protection state (readable by decoder / diagnostics)
 * Set by axiom_enc_xxx() when a write would exceed AXIOM_MAX_PAYLOAD_LEN.
 * Reset to false by the caller before each axiom_write() batch.
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_ENCODE_OVERFLOW_DETECTION
#define AXIOM_ENCODE_OVERFLOW_DETECTION 1
#endif

#ifdef __cplusplus
extern "C" {
#endif

#if AXIOM_ENCODE_OVERFLOW_DETECTION
extern volatile bool axiom_encode_overflow;
#endif

/* ---------------------------------------------------------------------------
 * Payload encoding constants
 * --------------------------------------------------------------------------- */
#define AXIOM_TAG_SIZE 0u  /* Wire v2 normal arguments carry no type-tag byte. */

/* ---------------------------------------------------------------------------
 * Type-safe payload encoding helpers
 * Each function writes: [value (N bytes)] in the wire v2 packed payload.
 * Overflow check: pos + value_bytes <= AXIOM_MAX_PAYLOAD_LEN
 * --------------------------------------------------------------------------- */

/**
 * @brief Encode a boolean value into the payload buffer.
 * @param buf   Payload buffer (caller owns memory)
 * @param pos   Current write position, updated on success
 * @param val   Value to encode
 *
 * Overflow protection: silently skips write if buf cannot fit
 * value(1) = 1 byte.
 * When AXIOM_ENCODE_OVERFLOW_DETECTION is enabled, axiom_encode_overflow
 * is set to true on overflow.
 */
static inline void axiom_enc_bool(uint8_t *buf, uint8_t *pos, bool val) {
    if (*pos + 1u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = val ? 1u : 0u;
}

static inline void axiom_enc_u8(uint8_t *buf, uint8_t *pos, uint8_t val) {
    /* Required: value(1) = 1 byte */
    if (*pos + 1u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = val;
}

static inline void axiom_enc_i8(uint8_t *buf, uint8_t *pos, int8_t val) {
    /* Required: value(1) = 1 byte */
    if (*pos + 1u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = (uint8_t)val;
}

static inline void axiom_enc_u16(uint8_t *buf, uint8_t *pos, uint16_t val) {
    /* Required: value(2) = 2 bytes */
    if (*pos + 2u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)(val >> 8);
}

static inline void axiom_enc_i16(uint8_t *buf, uint8_t *pos, int16_t val) {
    /* Required: value(2) = 2 bytes */
    if (*pos + 2u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    uint16_t u = (uint16_t)val;
    buf[(*pos)++] = (uint8_t)(u & 0xFFu);
    buf[(*pos)++] = (uint8_t)(u >> 8);
}

static inline void axiom_enc_u32(uint8_t *buf, uint8_t *pos, uint32_t val) {
    /* Required: value(4) = 4 bytes */
    if (*pos + 4u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(val >> 24);
}

static inline void axiom_enc_i32(uint8_t *buf, uint8_t *pos, int32_t val) {
    /* Required: value(4) = 4 bytes */
    if (*pos + 4u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    uint32_t u = (uint32_t)val; /* cast to unsigned to avoid sign-extension */
    buf[(*pos)++] = (uint8_t)(u & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(u >> 24);
}

static inline void axiom_enc_f32(uint8_t *buf, uint8_t *pos, float val) {
    /* Required: value(4) = 4 bytes */
    if (*pos + 4u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    uint32_t u;
    memcpy(&u, &val, sizeof(u));
    buf[(*pos)++] = (uint8_t)(u & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((u >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(u >> 24);
}

static inline void axiom_enc_timestamp(uint8_t *buf, uint8_t *pos, uint32_t val) {
    /* Required: value(4) = 4 bytes */
    if (*pos + 4u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = (uint8_t)(val & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 8) & 0xFFu);
    buf[(*pos)++] = (uint8_t)((val >> 16) & 0xFFu);
    buf[(*pos)++] = (uint8_t)(val >> 24);
}

static inline void axiom_enc_bytes(uint8_t *buf, uint8_t *pos, const uint8_t *data, uint8_t len) {
    /* Required: length(1) + data(len) bytes */
    if ((uint16_t)(*pos) + (uint16_t)len + 1u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = len;
    for (uint8_t i = 0; i < len; ++i) {
        buf[(*pos)++] = data[i];
    }
}

/* Reserved system probes retain typed fields because their value type is not
 * described by an application event dictionary. */
static inline bool axiom_enc_tagged_prefix(uint8_t *buf, uint8_t *pos,
                                           uint8_t tag, uint8_t value_size) {
    if ((uint16_t)(*pos) + 1u + (uint16_t)value_size > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return false;
    }
    buf[(*pos)++] = tag;
    return true;
}

static inline void axiom_enc_tagged_bool(uint8_t *buf, uint8_t *pos, bool val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_BOOL, 1u)) {
        axiom_enc_bool(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_u8(uint8_t *buf, uint8_t *pos, uint8_t val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_U8, 1u)) {
        axiom_enc_u8(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_i8(uint8_t *buf, uint8_t *pos, int8_t val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_I8, 1u)) {
        axiom_enc_i8(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_u16(uint8_t *buf, uint8_t *pos, uint16_t val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_U16, 2u)) {
        axiom_enc_u16(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_i16(uint8_t *buf, uint8_t *pos, int16_t val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_I16, 2u)) {
        axiom_enc_i16(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_u32(uint8_t *buf, uint8_t *pos, uint32_t val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_U32, 4u)) {
        axiom_enc_u32(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_i32(uint8_t *buf, uint8_t *pos, int32_t val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_I32, 4u)) {
        axiom_enc_i32(buf, pos, val);
    }
}

static inline void axiom_enc_tagged_f32(uint8_t *buf, uint8_t *pos, float val) {
    if (axiom_enc_tagged_prefix(buf, pos, AXIOM_TYPE_F32, 4u)) {
        axiom_enc_f32(buf, pos, val);
    }
}

/* Metadata: [tag][mode=FILE_ID][file_id:u16][line:u16]. */
static inline void axiom_enc_meta_location_file_id(uint8_t *buf, uint8_t *pos,
                                                    uint16_t file_id, uint16_t line) {
    if (*pos + 6u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = AXIOM_TYPE_META_LOCATION;
    buf[(*pos)++] = AXIOM_CFG_LOCATION_MODE_FILE_ID;
    buf[(*pos)++] = (uint8_t)(file_id & 0xFFu);
    buf[(*pos)++] = (uint8_t)(file_id >> 8);
    buf[(*pos)++] = (uint8_t)(line & 0xFFu);
    buf[(*pos)++] = (uint8_t)(line >> 8);
}

/* Metadata: [tag][mode=HASH][file_hash:u16][line:u16][func_hash:u16]. */
static inline void axiom_enc_meta_location_hash(uint8_t *buf, uint8_t *pos,
                                                uint16_t file_hash, uint16_t line,
                                                uint16_t func_hash) {
    if (*pos + 8u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = AXIOM_TYPE_META_LOCATION;
    buf[(*pos)++] = AXIOM_CFG_LOCATION_MODE_HASH;
    buf[(*pos)++] = (uint8_t)(file_hash & 0xFFu);
    buf[(*pos)++] = (uint8_t)(file_hash >> 8);
    buf[(*pos)++] = (uint8_t)(line & 0xFFu);
    buf[(*pos)++] = (uint8_t)(line >> 8);
    buf[(*pos)++] = (uint8_t)(func_hash & 0xFFu);
    buf[(*pos)++] = (uint8_t)(func_hash >> 8);
}

#define AXIOM_METADATA_ID_LEN 8u

/* Metadata: [tag][metadata_id:8]. This selects host decode metadata, not an ELF image. */
static inline void axiom_enc_meta_identity(uint8_t *buf, uint8_t *pos,
                                           const uint8_t metadata_id[AXIOM_METADATA_ID_LEN]) {
    if (*pos + 9u > AXIOM_MAX_PAYLOAD_LEN) {
#if AXIOM_ENCODE_OVERFLOW_DETECTION
        axiom_encode_overflow = true;
#endif
        return;
    }
    buf[(*pos)++] = AXIOM_TYPE_META_IDENTITY;
    for (uint8_t i = 0; i < AXIOM_METADATA_ID_LEN; ++i) {
        buf[(*pos)++] = metadata_id[i];
    }
}

/* ---------------------------------------------------------------------------
 * C11 _Generic dispatcher for a single argument
 * Note: double literals (e.g., 3.14) are NOT supported.
 * Use float literals (e.g., 3.14f) or explicit (float)3.14 cast.
 * --------------------------------------------------------------------------- */
#define _AXIOM_ENCODE_ONE(buf, pos, arg) \
    _Generic((arg), \
        bool:     axiom_enc_bool, \
        uint8_t:  axiom_enc_u8,  \
        int8_t:   axiom_enc_i8,  \
        uint16_t: axiom_enc_u16, \
        int16_t:  axiom_enc_i16, \
        uint32_t: axiom_enc_u32, \
        int32_t:  axiom_enc_i32, \
        float:    axiom_enc_f32  \
    )(buf, &(pos), arg)

#define _AXIOM_ENCODE_TAGGED_ONE(buf, pos, arg) \
    _Generic((arg), \
        bool:     axiom_enc_tagged_bool, \
        uint8_t:  axiom_enc_tagged_u8,  \
        int8_t:   axiom_enc_tagged_i8,  \
        uint16_t: axiom_enc_tagged_u16, \
        int16_t:  axiom_enc_tagged_i16, \
        uint32_t: axiom_enc_tagged_u32, \
        int32_t:  axiom_enc_tagged_i32, \
        float:    axiom_enc_tagged_f32  \
    )(buf, &(pos), arg)

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_ENCODE_H */

/* ===== axiom_crc.h ===== */
#ifndef AXIOM_CRC_H
#define AXIOM_CRC_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * CRC-16/CCITT-FALSE
 * poly = 0x1021, init = 0xFFFF, no reflection, final XOR = 0x0000
 * --------------------------------------------------------------------------- */

uint16_t axiom_crc16(const uint8_t *data, size_t len);

/* Lookup table (256 bytes, stored in ROM) */
extern const uint16_t axiom_crc16_table[256];

/* Incremental CRC update — single byte */
static inline uint16_t axiom_crc16_update(uint16_t crc, uint8_t data) {
    return (uint16_t)((crc << 8) ^ axiom_crc16_table[((crc >> 8) ^ data) & 0xFFu]);
}

/* Incremental CRC update — byte range (N bytes) */
static inline uint16_t axiom_crc16_update_range(uint16_t crc, const uint8_t *data, size_t len) {
    for (size_t i = 0; i < len; ++i) {
        crc = axiom_crc16_update(crc, data[i]);
    }
    return crc;
}

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_CRC_H */

/* ===== axiom_ring.h ===== */
#ifndef AXIOM_RING_H
#define AXIOM_RING_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifndef AXIOM_RING_BUFFER_POLICY_DROP
#define AXIOM_RING_BUFFER_POLICY_DROP 0
#endif

#ifndef AXIOM_RING_BUFFER_POLICY_OVERWRITE
#define AXIOM_RING_BUFFER_POLICY_OVERWRITE 1
#endif

#ifndef AXIOM_RING_BUFFER_POLICY
#define AXIOM_RING_BUFFER_POLICY AXIOM_RING_BUFFER_POLICY_DROP
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * IRQ-safe SPSC RAM Ring Buffer with critical-section protection.
 * Single-producer (ISR or main loop), single-consumer (backend drain).
 * --------------------------------------------------------------------------- */

typedef struct {
    volatile uint32_t head;
    volatile uint32_t tail;
    uint32_t capacity;
    uint32_t mask;
    uintptr_t storage;
} axiom_ring_t;

/* Initialize ring buffer in the provided memory block. 
 * 'size' must be a power of two. */
void axiom_ring_init(axiom_ring_t *ring, uint8_t *buf, uint32_t size);

/* Write data to ring. Returns true on success, false if dropped. */
bool axiom_ring_write(axiom_ring_t *ring, const uint8_t *data, uint16_t len);

/* Write a chunk to the ring and optionally update CRC.
 * Internal use only, requires caller to handle critical section and capacity check. */
void axiom_ring_write_chunk(axiom_ring_t *ring, const uint8_t *data, uint16_t len, uint16_t *crc);

/* Read up to max_len bytes from ring. Returns bytes read. */
uint16_t axiom_ring_read(axiom_ring_t *ring, uint8_t *out, uint16_t max_len);

/* Peek at data without consuming. Returns bytes available. */
uint16_t axiom_ring_peek(const axiom_ring_t *ring, uint8_t *out, uint16_t max_len);

/* Advance tail by 'n' bytes without copying data.
 * Caller must have already read the data (e.g., via axiom_ring_peek).
 * Caller must ensure n <= axiom_ring_used(). */
void axiom_ring_consume(axiom_ring_t *ring, uint16_t n);

/* Bytes currently stored */
static inline uint32_t axiom_ring_used(const axiom_ring_t *ring) {
    return ring->head - ring->tail;
}

/* Free space */
static inline uint32_t axiom_ring_free(const axiom_ring_t *ring) {
    return ring->capacity - (ring->head - ring->tail);
}

/* Reset ring to empty */
void axiom_ring_reset(axiom_ring_t *ring);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_RING_H */

/* ===== axiom_timestamp.h ===== */
#ifndef AXIOM_TIMESTAMP_H
#define AXIOM_TIMESTAMP_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Compressed relative timestamp
 * Stores delta from previous event to reduce payload size.
 * --------------------------------------------------------------------------- */

typedef struct {
    uint32_t last_raw;
    uint32_t baseline; /* Reserved for future time-sync anchor (Unix epoch mapping) */
} axiom_timestamp_ctx_t;

/* Initialize timestamp context */
void axiom_timestamp_init(axiom_timestamp_ctx_t *ctx);

/* Encode current timestamp into up to 5 bytes. Returns encoded length (1..5). */
uint8_t axiom_timestamp_encode(axiom_timestamp_ctx_t *ctx, uint8_t *out);

/* Decode timestamp length from the first byte after the frame header.
 * Returns 1, 2, 3, or 5. Call this on frame[8] to locate payload_len.
 */
static inline uint8_t axiom_timestamp_decode_len(uint8_t first_byte) {
    if (first_byte >= 0xC0) {
        /* 0xFE and 0xFF both signal 5-byte full-delta encoding.
         * 0xC0..0xFD are 3-byte encoding (21-bit delta). */
        return (first_byte >= 0xFEu) ? 5 : 3;
    } else if (first_byte >= 0x80) {
        return 2;
    }
    return 1;
}

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_TIMESTAMP_H */

/* ===== axiom_filter.h ===== */
#ifndef AXIOM_FILTER_H
#define AXIOM_FILTER_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Runtime level/module filter and drop statistics
 * --------------------------------------------------------------------------- */

typedef struct {
    volatile uint32_t level_mask;   /* May be read in ISR context */
    volatile uint32_t module_mask;  /* May be read in ISR context */
    uint32_t drop_count;        /* Total dropped events */
    uint8_t  drop_module;       /* Module ID of last dropped event */
    uint16_t drop_event;        /* Event ID of last dropped event */
    bool     drop_pending;      /* True if drops occurred since last summary */
} axiom_filter_t;

/* Initialize filter (all levels/modules enabled, counters zeroed) */
void axiom_filter_init(axiom_filter_t *filter);

/* Check if event passes filter. Returns true if should emit. */
bool axiom_filter_check(axiom_filter_t *filter, axiom_level_t level, uint8_t module_id);

/* Record a drop. Call when event is discarded. */
void axiom_filter_drop(axiom_filter_t *filter, uint8_t module_id, uint16_t event_id);

/* Check and clear drop_pending flag. Returns true if a DROP_SUMMARY should be emitted.
 * Note: Drop summary is currently handled internally by axiom_write().
 * These functions are provided for external consumers (e.g., custom backends,
 * test harnesses) that need direct access to drop statistics. */
bool axiom_filter_drop_summary_ready(axiom_filter_t *filter);

/* Get drop counter and reset.
 * Provided for external consumers — see note above. */
uint32_t axiom_filter_drop_count_get_and_clear(axiom_filter_t *filter);

/* Runtime filter control — implementations are in axiom_event.c where s_filter is defined */
void axiom_level_mask_set(uint32_t mask);
uint32_t axiom_level_mask_get(void);
void axiom_module_mask_set(uint32_t mask);
uint32_t axiom_module_mask_get(void);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_FILTER_H */

/* ===== axiom_capsule.h ===== */
#ifndef AXIOM_CAPSULE_H
#define AXIOM_CAPSULE_H

#include <stdbool.h>
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif

/* Initialize volatile capsule capture state. Called by axiom_init(). */
void axiom_capsule_init(void);

/* Observe a complete wire frame after axiom_write() has assembled it. */
void axiom_capsule_observe_frame(const uint8_t *frame, uint16_t len, axiom_level_t level);

/* Add dropped-event statistics to the next capsule header. */
void axiom_capsule_record_drops(uint32_t lost);

/* Commit the captured capsule to the port flash backend. */
bool axiom_capsule_commit(void);

/* True when a valid RAM or flash capsule is available. */
bool axiom_capsule_present(void);

/* Read a complete valid capsule into out. Returns bytes copied, or 0 on error. */
uint32_t axiom_capsule_read(uint8_t *out, uint32_t max_len);

/* Clear volatile capture state and erase the configured flash capsule region. */
void axiom_capsule_clear(void);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_CAPSULE_H */

/* ===== axiom_frontend.h ===== */
#ifndef AXIOM_FRONTEND_H
#define AXIOM_FRONTEND_H


#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Profile control
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_PROFILE_DEV
#define AXIOM_PROFILE_DEV    0
#endif
#ifndef AXIOM_PROFILE_FIELD
#define AXIOM_PROFILE_FIELD  1
#endif
#ifndef AXIOM_PROFILE_PROD
#define AXIOM_PROFILE_PROD   2
#endif

#ifndef AXIOM_PROFILE
#define AXIOM_PROFILE AXIOM_PROFILE_DEV
#endif

/* ---------------------------------------------------------------------------
 * Variadic argument counting (GCC/Clang/MSVC compatible)
 * --------------------------------------------------------------------------- */
#define _AXIOM_ARG_N(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, N, ...) N
#define _AXIOM_NARG_(...) _AXIOM_ARG_N(__VA_ARGS__)
#define _AXIOM_NARG(...) _AXIOM_NARG_(0, ##__VA_ARGS__, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)

#define _AXIOM_CONCAT2(a, b) a ## b
#define _AXIOM_CONCAT(a, b)  _AXIOM_CONCAT2(a, b)

/* ---------------------------------------------------------------------------
 * Core write declaration (defined in axiom_event.c)
 * --------------------------------------------------------------------------- */
void axiom_write(axiom_level_t level, uint8_t module_id, uint16_t event_id,
                 const uint8_t *payload, uint8_t payload_len);
void axiom_init(void);
void axiom_flush(void);

/* Runtime filter control — declared in axiom_filter.h, exposed here for convenience.
 * void axiom_level_mask_set(uint32_t mask);
 * uint32_t axiom_level_mask_get(void);
 * void axiom_module_mask_set(uint32_t mask);
 * uint32_t axiom_module_mask_get(void);
 */

/* ---------------------------------------------------------------------------
 * FNV-1a 16-bit hash (runtime, for key hashing)
 * --------------------------------------------------------------------------- */
static inline uint16_t _axiom_fnv1a_16(const char *s) {
    uint16_t h = 0x811cu;
    while (*s) {
        h ^= (uint16_t)(unsigned char)(*s++);
        h *= 0x0103u;
    }
    return h;
}

/* ---------------------------------------------------------------------------
 * Optional source-location metadata
 * --------------------------------------------------------------------------- */
#if AXIOM_CFG_LOCATION_MODE == AXIOM_CFG_LOCATION_MODE_FILE_ID
#define _AXIOM_APPEND_LOCATION(buf, pos) \
    axiom_enc_meta_location_file_id((buf), &(pos), (uint16_t)AXIOM_SOURCE_FILE_ID, (uint16_t)__LINE__)
#elif AXIOM_CFG_LOCATION_MODE == AXIOM_CFG_LOCATION_MODE_HASH
#if AXIOM_CFG_LOCATION_FUNCTION
#define _AXIOM_APPEND_LOCATION(buf, pos) \
    axiom_enc_meta_location_hash((buf), &(pos), _axiom_fnv1a_16(__FILE__), (uint16_t)__LINE__, _axiom_fnv1a_16(__func__))
#else
#define _AXIOM_APPEND_LOCATION(buf, pos) \
    axiom_enc_meta_location_hash((buf), &(pos), _axiom_fnv1a_16(__FILE__), (uint16_t)__LINE__, 0u)
#endif
#else
#define _AXIOM_APPEND_LOCATION(buf, pos) ((void)0)
#endif

#define _AXIOM_EMIT_BUFFERED(level, mod, evt, buf, pos) \
    do { _AXIOM_APPEND_LOCATION((buf), pos); \
         axiom_write((level), (mod), (evt), (buf), (pos)); } while(0)

/* System-reserved metadata identity event used by host bundle-store selection. */
#define AXIOM_SYSTEM_MODULE_ID          0x00u
#define AXIOM_SYSTEM_EVENT_DROP_SUMMARY 0x0001u
#define AXIOM_SYSTEM_EVENT_METADATA_ID  0x0002u

static inline void axiom_emit_metadata_id(const uint8_t metadata_id[AXIOM_METADATA_ID_LEN]) {
    uint8_t b[AXIOM_MAX_PAYLOAD_LEN];
    uint8_t p = 0;
    axiom_enc_meta_identity(b, &p, metadata_id);
    axiom_write(AXIOM_LEVEL_INFO, AXIOM_SYSTEM_MODULE_ID, AXIOM_SYSTEM_EVENT_METADATA_ID, b, p);
}

/* ---------------------------------------------------------------------------
 * AX_EVT — Structured Event (always compiled, all profiles)
 * --------------------------------------------------------------------------- */
#if AXIOM_CFG_LOCATION_MODE == AXIOM_CFG_LOCATION_MODE_NONE
#define _AXIOM_EVT_0(level, mod, evt) \
    axiom_write((level), (mod), (evt), NULL, 0)
#else
#define _AXIOM_EVT_0(level, mod, evt) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)
#endif

#define _AXIOM_EVT_1(level, mod, evt, a1) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_2(level, mod, evt, a1, a2) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_3(level, mod, evt, a1, a2, a3) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_4(level, mod, evt, a1, a2, a3, a4) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_5(level, mod, evt, a1, a2, a3, a4, a5) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_6(level, mod, evt, a1, a2, a3, a4, a5, a6) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_ENCODE_ONE(_b, _p, a6); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_7(level, mod, evt, a1, a2, a3, a4, a5, a6, a7) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_ENCODE_ONE(_b, _p, a6); \
         _AXIOM_ENCODE_ONE(_b, _p, a7); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_8(level, mod, evt, a1, a2, a3, a4, a5, a6, a7, a8) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_ENCODE_ONE(_b, _p, a1); \
         _AXIOM_ENCODE_ONE(_b, _p, a2); \
         _AXIOM_ENCODE_ONE(_b, _p, a3); \
         _AXIOM_ENCODE_ONE(_b, _p, a4); \
         _AXIOM_ENCODE_ONE(_b, _p, a5); \
         _AXIOM_ENCODE_ONE(_b, _p, a6); \
         _AXIOM_ENCODE_ONE(_b, _p, a7); \
         _AXIOM_ENCODE_ONE(_b, _p, a8); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_EVT_DISPATCH(level, mod, evt, ...) \
    _AXIOM_CONCAT(_AXIOM_EVT_, _AXIOM_NARG(__VA_ARGS__))(level, mod, evt, ##__VA_ARGS__)

#define AX_EVT(level, mod, evt, ...) \
    _AXIOM_EVT_DISPATCH(AXIOM_LEVEL_##level, mod, evt, ##__VA_ARGS__)

#define AX_FAULT(mod, evt, ...) \
    _AXIOM_EVT_DISPATCH(AXIOM_LEVEL_FAULT, mod, evt, ##__VA_ARGS__)

/* ---------------------------------------------------------------------------
 * AX_LOG — Development logging (PROD profile = no-op)
 * Outputs plain text via axiom_port_string_out(). Does NOT enter binary protocol.
 * --------------------------------------------------------------------------- */
#if (AXIOM_PROFILE == AXIOM_PROFILE_DEV) || (AXIOM_PROFILE == AXIOM_PROFILE_FIELD)

#define AX_LOG(msg)         do { axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_DEBUG(msg)   do { axiom_port_string_out("[DEBUG] "); axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_INFO(msg)    do { axiom_port_string_out("[INFO] ");  axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_WARN(msg)    do { axiom_port_string_out("[WARN] ");  axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)
#define AX_LOG_ERROR(msg)   do { axiom_port_string_out("[ERROR] "); axiom_port_string_out(msg); axiom_port_string_out("\n"); } while(0)

#else /* PROD */

#define AX_LOG(msg)         ((void)0)
#define AX_LOG_DEBUG(msg)   ((void)0)
#define AX_LOG_INFO(msg)    ((void)0)
#define AX_LOG_WARN(msg)    ((void)0)
#define AX_LOG_ERROR(msg)   ((void)0)

#endif

/* ---------------------------------------------------------------------------
 * AX_PROBE — Timing probe (PROD profile = no-op)
 * Reserved system event with typed fields: its varying value is intentionally
 * decodable without an application dictionary under wire v2.
 * --------------------------------------------------------------------------- */
#if (AXIOM_PROFILE == AXIOM_PROFILE_DEV) || (AXIOM_PROFILE == AXIOM_PROFILE_FIELD)

#define AX_PROBE(tag, value) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         uint16_t _th = _axiom_fnv1a_16(tag); \
         axiom_enc_tagged_u16(_b, &_p, _th); \
         _AXIOM_ENCODE_TAGGED_ONE(_b, _p, value); \
         axiom_write(AXIOM_LEVEL_DEBUG, 0, 0, _b, _p); } while(0)

#else /* PROD */

#define AX_PROBE(tag, value) ((void)0)

#endif

/* ---------------------------------------------------------------------------
 * AX_KV — Key-Value event (always compiled)
 * Keys are hashed at compile-time to 16-bit IDs via FNV-1a.
 * --------------------------------------------------------------------------- */
#define _AXIOM_KV_KEYVAL(buf, pos, key, val) \
    do { uint16_t _kh = _axiom_fnv1a_16(key); \
         axiom_enc_u16(buf, &(pos), _kh); \
         _AXIOM_ENCODE_ONE(buf, pos, val); \
    } while(0)

#define _AXIOM_KV_2(level, mod, evt, k1, v1) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_KV_KEYVAL(_b, _p, k1, v1); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define _AXIOM_KV_4(level, mod, evt, k1, v1, k2, v2) \
    do { uint8_t _b[AXIOM_MAX_PAYLOAD_LEN]; uint8_t _p = 0; \
         _AXIOM_KV_KEYVAL(_b, _p, k1, v1); \
         _AXIOM_KV_KEYVAL(_b, _p, k2, v2); \
         _AXIOM_EMIT_BUFFERED((level), (mod), (evt), _b, _p); } while(0)

#define AX_KV(level, mod, evt, ...) \
    _AXIOM_CONCAT(_AXIOM_KV_, _AXIOM_NARG(__VA_ARGS__))(AXIOM_LEVEL_##level, mod, evt, ##__VA_ARGS__)

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_FRONTEND_H */

/* ===== axiom_backend.h ===== */
#ifndef AXIOM_BACKEND_H
#define AXIOM_BACKEND_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * Backend Capability Flags
 * Used by the backend registry to advertise transport capabilities.
 * Query via backend.caps at registration or discovery time.
 * --------------------------------------------------------------------------- */
#define AXIOM_BACKEND_CAP_MEMORY  (1u << 0) /* In-memory ring capture           */
#define AXIOM_BACKEND_CAP_UART    (1u << 1) /* Serial UART transport            */
#define AXIOM_BACKEND_CAP_USB     (1u << 2) /* USB CDC / bulk transport          */
#define AXIOM_BACKEND_CAP_RTT     (1u << 3) /* SEGGER RTT transport             */
#define AXIOM_BACKEND_CAP_SWO     (1u << 4) /* ARM SWO stimulus port            */
#define AXIOM_BACKEND_CAP_CANFD   (1u << 5) /* CAN-FD transport                 */
#define AXIOM_BACKEND_CAP_CAPSULE (1u << 6) /* Fault capsule (flash-persistent) */

/* ---------------------------------------------------------------------------
 * Backend Contract
 * The first field `size` enables forward-compatible struct evolution:
 * - Old backends (zero-initialized) have size==0, treated as legacy v1 layout.
 * - New backends set size via AXIOM_BACKEND_INIT() so the registry can
 *   detect the layout version and safely access fields added in future minor
 *   releases without breaking ABI.
 * --------------------------------------------------------------------------- */
typedef struct {
    uint16_t size;              /* sizeof(this struct) at compile time */
    const char *name;
    uint32_t caps;

    int  (*write)(const uint8_t *buf, uint16_t len, void *ctx);
    int  (*ready)(void *ctx);
    int  (*flush)(void *ctx);
    int  (*panic_write)(const uint8_t *buf, uint16_t len, void *ctx);

    void (*on_drop)(uint32_t lost, void *ctx);
    void *ctx;
} axiom_backend_t;

/* Designated-initializer wrapper: fills size automatically.
 * Example: static const axiom_backend_t my_be = AXIOM_BACKEND_INIT(
 *     .name = "uart", .write = uart_write, .ctx = &uart_ctx); */
#define AXIOM_BACKEND_INIT(...)  { .size = sizeof(axiom_backend_t), __VA_ARGS__ }

/* ---------------------------------------------------------------------------
 * Backend Registry — Error Codes
 * --------------------------------------------------------------------------- */
typedef enum {
    AXIOM_BACKEND_OK         =  0,
    AXIOM_BACKEND_ERR_NULL   = -1,  /* backend or write callback is NULL */
    AXIOM_BACKEND_ERR_FULL   = -2,  /* registry full (>= AXIOM_BACKEND_MAX) */
    AXIOM_BACKEND_ERR_STRUCT = -3,  /* struct size mismatch — recompile backend */
} axiom_backend_err_t;

#ifndef AXIOM_BACKEND_MAX
#define AXIOM_BACKEND_MAX 4
#endif

/* ---------------------------------------------------------------------------
 * Backend Degradation & Recovery
 *
 * After N consecutive write failures, a backend is temporarily disabled
 * (soft-disabled) for AXIOM_BACKEND_RECOVERY_US microseconds. This
 * prevents a broken UART/USB from blocking other backends indefinitely.
 * Auto-recovery is attempted during axiom_backend_dispatch().
 *
 * Enable via AXIOM_BACKEND_DEGRADATION=1 (default).
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_BACKEND_DEGRADATION
#define AXIOM_BACKEND_DEGRADATION 1
#endif

#if AXIOM_BACKEND_DEGRADATION
    #ifndef AXIOM_BACKEND_FAIL_THRESHOLD
    #define AXIOM_BACKEND_FAIL_THRESHOLD 5
    #endif
    #ifndef AXIOM_BACKEND_RECOVERY_US
    #define AXIOM_BACKEND_RECOVERY_US 1000000u /* 1 second */
    #endif
#endif

/* Register a backend. Returns AXIOM_BACKEND_OK on success, negative on error.
 * MUST be called before any axiom_write() — not thread-safe. */
int axiom_backend_register(const axiom_backend_t *backend);

/* Dispatch a frame to all registered backends.
 * Called internally by axiom_flush() after ring buffer peek+consume.
 * Includes auto-recovery of soft-disabled backends. */
void axiom_backend_dispatch(const uint8_t *frame, uint16_t len);

/* Flush all backends that provide a flush callback. */
void axiom_backend_flush_all(void);

/* Panic write to all backends that provide panic_write.
 * Bypasses degradation — panic always attempts all backends. */
void axiom_backend_panic_write(const uint8_t *frame, uint16_t len);

/* Query per-backend health status (for diagnostics / self-report).
 * Returns number of currently active (non-disabled) backends. */
uint8_t axiom_backend_active_count(void);

/* Query total number of registered backends.
 * Returns count regardless of degradation state. */
uint8_t axiom_backend_count(void);

#ifdef __cplusplus
}
#endif

#endif /* AXIOM_BACKEND_H */

/* ===== axiom_port_generic.c ===== */

/* ============================================================================
 * Generic host/default port implementations
 * ============================================================================
 *
 * On ELF targets (Linux, most embedded GCC toolchains), these symbols are
 * marked weak so the user can override them by providing strong-symbol
 * implementations in another translation unit.
 *
 * On Windows/PE targets (MinGW, MSVC), weak symbol support is limited or
 * non-existent. We therefore provide regular (strong) defaults.  If you need
 * to override on Windows, either:
 *   1. Edit this file directly, or
 *   2. Provide an object file with the same symbols **before** this one in
 *      the link command.
 * ============================================================================ */

#if (defined(__GNUC__) || defined(__clang__)) && !defined(_WIN32)
#define AXIOM_WEAK __attribute__((weak))
#else
#define AXIOM_WEAK
#endif

#if defined(AXIOM_HOST_TESTING)
#include <string.h>

uint32_t g_axiom_port_simulated_time = 0u;
uint8_t g_axiom_port_reset_reason = 0u;
uint8_t g_axiom_port_fault_snapshot_data[64];
uint8_t g_axiom_port_fault_snapshot_len = 0u;
uint8_t g_axiom_port_flash_storage[AXIOM_HOST_FLASH_SIZE];
uint32_t g_axiom_port_flash_erase_calls = 0u;
uint32_t g_axiom_port_flash_write_calls = 0u;
uint32_t g_axiom_port_flash_read_calls = 0u;
uint32_t g_axiom_port_flash_write_limit = AXIOM_HOST_FLASH_SIZE;
int g_axiom_port_flash_fail_erase = 0;
int g_axiom_port_flash_fail_write = 0;
int g_axiom_port_flash_fail_read = 0;

AXIOM_WEAK uint32_t axiom_port_timestamp(void) { return g_axiom_port_simulated_time; }
#else
AXIOM_WEAK uint32_t axiom_port_timestamp(void) { return 0u; }
#endif

AXIOM_WEAK void axiom_port_critical_enter(void) { }

AXIOM_WEAK void axiom_port_critical_exit(void) { }

AXIOM_WEAK void axiom_port_string_out(const char *str) {
    (void)str;
}

AXIOM_WEAK void axiom_port_fault_hook(uint8_t module_id, uint16_t event_id,
                                       const uint8_t *payload, uint8_t payload_len) {
    (void)module_id; (void)event_id; (void)payload; (void)payload_len;
}

AXIOM_WEAK uint8_t axiom_port_reset_reason(void) {
#if defined(AXIOM_HOST_TESTING)
    return g_axiom_port_reset_reason;
#else
    return 0u;
#endif
}

AXIOM_WEAK uint8_t axiom_port_fault_snapshot(uint8_t *buf, uint8_t max_len) {
#if defined(AXIOM_HOST_TESTING)
    if (!buf || max_len == 0u) {
        return 0u;
    }
    uint8_t n = g_axiom_port_fault_snapshot_len < max_len ? g_axiom_port_fault_snapshot_len : max_len;
    memcpy(buf, g_axiom_port_fault_snapshot_data, n);
    return n;
#else
    (void)buf; (void)max_len;
    return 0;
#endif
}

AXIOM_WEAK int axiom_port_flash_erase(uint32_t addr, uint32_t len) {
#if defined(AXIOM_HOST_TESTING)
    g_axiom_port_flash_erase_calls++;
    if (g_axiom_port_flash_fail_erase || addr > AXIOM_HOST_FLASH_SIZE || len > AXIOM_HOST_FLASH_SIZE - addr) {
        return -1;
    }
    memset(g_axiom_port_flash_storage + addr, 0xFF, len);
    return 0;
#else
    (void)addr; (void)len;
    return -1;
#endif
}

AXIOM_WEAK int axiom_port_flash_write(uint32_t addr, const uint8_t *data, uint32_t len) {
#if defined(AXIOM_HOST_TESTING)
    g_axiom_port_flash_write_calls++;
    if (g_axiom_port_flash_fail_write || !data ||
        addr > AXIOM_HOST_FLASH_SIZE || len > AXIOM_HOST_FLASH_SIZE - addr) {
        return -1;
    }
    uint32_t writable = len;
    if (writable > g_axiom_port_flash_write_limit) {
        writable = g_axiom_port_flash_write_limit;
    }
    memcpy(g_axiom_port_flash_storage + addr, data, writable);
    if (writable != len) {
        return -1;
    }
    return 0;
#else
    (void)addr; (void)data; (void)len;
    return -1;
#endif
}

AXIOM_WEAK int axiom_port_flash_read(uint32_t addr, uint8_t *out, uint32_t len) {
#if defined(AXIOM_HOST_TESTING)
    g_axiom_port_flash_read_calls++;
    if (g_axiom_port_flash_fail_read || !out ||
        addr > AXIOM_HOST_FLASH_SIZE || len > AXIOM_HOST_FLASH_SIZE - addr) {
        return -1;
    }
    memcpy(out, g_axiom_port_flash_storage + addr, len);
    return 0;
#else
    (void)addr; (void)out; (void)len;
    return -1;
#endif
}

#if defined(AXIOM_HOST_TESTING)
void axiom_port_host_flash_reset(void) {
    memset(g_axiom_port_flash_storage, 0xFF, sizeof(g_axiom_port_flash_storage));
    memset(g_axiom_port_fault_snapshot_data, 0, sizeof(g_axiom_port_fault_snapshot_data));
    g_axiom_port_reset_reason = 0u;
    g_axiom_port_fault_snapshot_len = 0u;
    g_axiom_port_flash_erase_calls = 0u;
    g_axiom_port_flash_write_calls = 0u;
    g_axiom_port_flash_read_calls = 0u;
    g_axiom_port_flash_write_limit = AXIOM_HOST_FLASH_SIZE;
    g_axiom_port_flash_fail_erase = 0;
    g_axiom_port_flash_fail_write = 0;
    g_axiom_port_flash_fail_read = 0;
}
#endif

/* ===== axiom_crc.c ===== */

/* CRC-16/CCITT-FALSE lookup table */
const uint16_t axiom_crc16_table[256] = {
    0x0000, 0x1021, 0x2042, 0x3063, 0x4084, 0x50A5, 0x60C6, 0x70E7,
    0x8108, 0x9129, 0xA14A, 0xB16B, 0xC18C, 0xD1AD, 0xE1CE, 0xF1EF,
    0x1231, 0x0210, 0x3273, 0x2252, 0x52B5, 0x4294, 0x72F7, 0x62D6,
    0x9339, 0x8318, 0xB37B, 0xA35A, 0xD3BD, 0xC39C, 0xF3FF, 0xE3DE,
    0x2462, 0x3443, 0x0420, 0x1401, 0x64E6, 0x74C7, 0x44A4, 0x5485,
    0xA56A, 0xB54B, 0x8528, 0x9509, 0xE5EE, 0xF5CF, 0xC5AC, 0xD58D,
    0x3653, 0x2672, 0x1611, 0x0630, 0x76D7, 0x66F6, 0x5695, 0x46B4,
    0xB75B, 0xA77A, 0x9719, 0x8738, 0xF7DF, 0xE7FE, 0xD79D, 0xC7BC,
    0x48C4, 0x58E5, 0x6886, 0x78A7, 0x0840, 0x1861, 0x2802, 0x3823,
    0xC9CC, 0xD9ED, 0xE98E, 0xF9AF, 0x8948, 0x9969, 0xA90A, 0xB92B,
    0x5AF5, 0x4AD4, 0x7AB7, 0x6A96, 0x1A71, 0x0A50, 0x3A33, 0x2A12,
    0xDBFD, 0xCBDC, 0xFBBF, 0xEB9E, 0x9B79, 0x8B58, 0xBB3B, 0xAB1A,
    0x6CA6, 0x7C87, 0x4CE4, 0x5CC5, 0x2C22, 0x3C03, 0x0C60, 0x1C41,
    0xEDAE, 0xFD8F, 0xCDEC, 0xDDCD, 0xAD2A, 0xBD0B, 0x8D68, 0x9D49,
    0x7E97, 0x6EB6, 0x5ED5, 0x4EF4, 0x3E13, 0x2E32, 0x1E51, 0x0E70,
    0xFF9F, 0xEFBE, 0xDFDD, 0xCFFC, 0xBF1B, 0xAF3A, 0x9F59, 0x8F78,
    0x9188, 0x81A9, 0xB1CA, 0xA1EB, 0xD10C, 0xC12D, 0xF14E, 0xE16F,
    0x1080, 0x00A1, 0x30C2, 0x20E3, 0x5004, 0x4025, 0x7046, 0x6067,
    0x83B9, 0x9398, 0xA3FB, 0xB3DA, 0xC33D, 0xD31C, 0xE37F, 0xF35E,
    0x02B1, 0x1290, 0x22F3, 0x32D2, 0x4235, 0x5214, 0x6277, 0x7256,
    0xB5EA, 0xA5CB, 0x95A8, 0x8589, 0xF56E, 0xE54F, 0xD52C, 0xC50D,
    0x34E2, 0x24C3, 0x14A0, 0x0481, 0x7466, 0x6447, 0x5424, 0x4405,
    0xA7DB, 0xB7FA, 0x8799, 0x97B8, 0xE75F, 0xF77E, 0xC71D, 0xD73C,
    0x26D3, 0x36F2, 0x0691, 0x16B0, 0x6657, 0x7676, 0x4615, 0x5634,
    0xD94C, 0xC96D, 0xF90E, 0xE92F, 0x99C8, 0x89E9, 0xB98A, 0xA9AB,
    0x5844, 0x4865, 0x7806, 0x6827, 0x18C0, 0x08E1, 0x3882, 0x28A3,
    0xCB7D, 0xDB5C, 0xEB3F, 0xFB1E, 0x8BF9, 0x9BD8, 0xABBB, 0xBB9A,
    0x4A75, 0x5A54, 0x6A37, 0x7A16, 0x0AF1, 0x1AD0, 0x2AB3, 0x3A92,
    0xFD2E, 0xED0F, 0xDD6C, 0xCD4D, 0xBDAA, 0xAD8B, 0x9DE8, 0x8DC9,
    0x7C26, 0x6C07, 0x5C64, 0x4C45, 0x3CA2, 0x2C83, 0x1CE0, 0x0CC1,
    0xEF1F, 0xFF3E, 0xCF5D, 0xDF7C, 0xAF9B, 0xBFBA, 0x8FD9, 0x9FF8,
    0x6E17, 0x7E36, 0x4E55, 0x5E74, 0x2E93, 0x3EB2, 0x0ED1, 0x1EF0,
};

uint16_t axiom_crc16(const uint8_t *data, size_t len) {
    uint16_t crc = 0xFFFFu;
    for (size_t i = 0; i < len; ++i) {
        crc = (uint16_t)((crc << 8) ^ axiom_crc16_table[((crc >> 8) ^ data[i]) & 0xFFu]);
    }
    return crc;
}

/* ===== axiom_ring.c ===== */
#include <assert.h>
#include <string.h>
#include <stdint.h>

#ifndef AXIOM_RING_BUFFER_POLICY_DROP
#define AXIOM_RING_BUFFER_POLICY_DROP 0
#endif

#ifndef AXIOM_RING_BUFFER_POLICY_OVERWRITE
#define AXIOM_RING_BUFFER_POLICY_OVERWRITE 1
#endif

#ifndef AXIOM_RING_BUFFER_POLICY
#define AXIOM_RING_BUFFER_POLICY AXIOM_RING_BUFFER_POLICY_DROP
#endif

/* Internal: retrieve the data buffer pointer stored in the reserved field.
 * Returns a writable pointer to the ring buffer's backing storage. */
static inline uint8_t *ring_buf(axiom_ring_t *ring) {
    return (uint8_t *)ring->storage;
}

/* Helper: cast ring for const contexts (e.g. axiom_ring_peek) */
static inline const uint8_t *ring_buf_const(const axiom_ring_t *ring) {
    return (const uint8_t *)ring->storage;
}

void axiom_ring_write_chunk(axiom_ring_t *ring, const uint8_t *data, uint16_t len, uint16_t *crc) {
    uint32_t head = ring->head;
    uint32_t mask = ring->mask;
    uint8_t *buf = ring_buf(ring);
    
    for (uint16_t i = 0; i < len; ++i) {
        uint8_t b = data[i];
        buf[head & mask] = b;
        head++;
        if (crc) {
            *crc = axiom_crc16_update(*crc, b);
        }
    }
    ring->head = head;
}

void axiom_ring_init(axiom_ring_t *ring, uint8_t *buf, uint32_t size) {
    /* 验证 size 是 2 的幂，否则 mask 计算会出错 */
    assert((size & (size - 1)) == 0 && "Ring buffer size must be power of 2");

    ring->head = 0;
    ring->tail = 0;
    ring->capacity = size;
    ring->mask = size - 1;
    ring->storage = (uintptr_t)buf;
}

bool axiom_ring_write(axiom_ring_t *ring, const uint8_t *data, uint16_t len) {
    if (len == 0 || len > ring->capacity) {
        return false;
    }

    axiom_port_critical_enter();

    uint32_t head = ring->head;
    uint32_t tail = ring->tail;
    uint32_t cap  = ring->capacity;
    uint32_t mask = ring->mask;
    uint32_t used = head - tail;
    uint8_t *buf  = ring_buf(ring);

    if (used + len > cap) {
#if AXIOM_RING_BUFFER_POLICY == AXIOM_RING_BUFFER_POLICY_DROP
        axiom_port_critical_exit();
        return false;
#else
        /* OVERWRITE: blind advancement of tail to maintain O(1).
         * Decoder is responsible for handling partially overwritten frames.
         */
        tail = (head + len) - cap;
#endif
    }

    for (uint16_t i = 0; i < len; ++i) {
        buf[(head + i) & mask] = data[i];
    }
    ring->head = head + len;
    ring->tail = tail;

    axiom_port_critical_exit();
    return true;
}

uint16_t axiom_ring_read(axiom_ring_t *ring, uint8_t *out, uint16_t max_len) {
    if (!out || max_len == 0) return 0;

    axiom_port_critical_enter();

    uint32_t head = ring->head;
    uint32_t tail = ring->tail;
    uint32_t mask = ring->mask;
    uint32_t avail = head - tail;
    uint16_t n = (avail < max_len) ? (uint16_t)avail : max_len;
    uint8_t *buf = ring_buf(ring);

    for (uint16_t i = 0; i < n; ++i) {
        out[i] = buf[(tail + i) & mask];
    }
    ring->tail = tail + n;

    axiom_port_critical_exit();
    return n;
}

uint16_t axiom_ring_peek(const axiom_ring_t *ring, uint8_t *out, uint16_t max_len) {
    if (!out || max_len == 0) return 0;

    axiom_port_critical_enter();

    uint32_t head = ring->head;
    uint32_t tail = ring->tail;
    uint32_t mask = ring->mask;
    uint32_t avail = head - tail;
    uint16_t n = (avail < max_len) ? (uint16_t)avail : max_len;
    const uint8_t *buf = ring_buf_const(ring);

    for (uint16_t i = 0; i < n; ++i) {
        out[i] = buf[(tail + i) & mask];
    }

    axiom_port_critical_exit();
    return n;
}

void axiom_ring_consume(axiom_ring_t *ring, uint16_t n) {
    axiom_port_critical_enter();
    ring->tail += n;
    axiom_port_critical_exit();
}

void axiom_ring_reset(axiom_ring_t *ring) {
    axiom_port_critical_enter();
    ring->head = 0;
    ring->tail = 0;
    axiom_port_critical_exit();
}

/* ===== axiom_timestamp.c ===== */

void axiom_timestamp_init(axiom_timestamp_ctx_t *ctx) {
    ctx->last_raw = 0;
    ctx->baseline = 0;
}

uint8_t axiom_timestamp_encode(axiom_timestamp_ctx_t *ctx, uint8_t *out) {
    uint32_t raw = axiom_port_timestamp();
    uint32_t delta = raw - ctx->last_raw;
    ctx->last_raw = raw;

    /* Variable-length encoding: smaller deltas use fewer bytes */
    if (delta <= 0x7Fu) {
        out[0] = (uint8_t)(delta & 0x7Fu);
        return 1;
    } else if (delta <= 0x3FFFu) {
        out[0] = (uint8_t)(0x80u | ((delta >> 8) & 0x3Fu));
        out[1] = (uint8_t)(delta & 0xFFu);
        return 2;
    } else if (delta <= 0x1FFFFFu) {
        out[0] = (uint8_t)(0xC0u | ((delta >> 16) & 0x1Fu));
        out[1] = (uint8_t)((delta >> 8) & 0xFFu);
        out[2] = (uint8_t)(delta & 0xFFu);
        return 3;
    } else {
        /* 使用 0xFE 标记大 delta，0xFF 可以正常出现在数据中 */
        out[0] = 0xFEu;
        out[1] = (uint8_t)(delta & 0xFFu);
        out[2] = (uint8_t)((delta >> 8) & 0xFFu);
        out[3] = (uint8_t)((delta >> 16) & 0xFFu);
        out[4] = (uint8_t)((delta >> 24) & 0xFFu);
        return 5;
    }
}

/* ===== axiom_filter.c ===== */

void axiom_filter_init(axiom_filter_t *filter) {
    filter->level_mask  = 0xFFFFFFFFu;
    filter->module_mask = 0xFFFFFFFFu;
    filter->drop_count  = 0;
    filter->drop_module = 0;
    filter->drop_event  = 0;
    filter->drop_pending = false;
}

bool axiom_filter_check(axiom_filter_t *filter, axiom_level_t level, uint8_t module_id) {
    if (level >= AXIOM_LEVEL_MAX) return false;
    if ((filter->level_mask & (1u << (uint32_t)level)) == 0) return false;
    /* 32-bit mask limits per-module filtering to module_id 0..(AXIOM_MODULE_MAX-1).
     * Modules with id >= AXIOM_MODULE_MAX always pass the filter (no masking applied). */
    if (module_id < AXIOM_MODULE_MAX && (filter->module_mask & (1u << (uint32_t)module_id)) == 0) return false;
    return true;
}

void axiom_filter_drop(axiom_filter_t *filter, uint8_t module_id, uint16_t event_id) {
    filter->drop_count++;
    filter->drop_module = module_id;
    filter->drop_event  = event_id;
    filter->drop_pending = true;
}

bool axiom_filter_drop_summary_ready(axiom_filter_t *filter) {
    return filter->drop_pending;
}

uint32_t axiom_filter_drop_count_get_and_clear(axiom_filter_t *filter) {
    uint32_t count = filter->drop_count;
    filter->drop_count = 0;
    filter->drop_pending = false;
    filter->drop_module = 0;
    filter->drop_event  = 0;
    return count;
}

/* ===== axiom_capsule.c ===== */


#include <string.h>

#if AXIOM_CAPSULE_ENABLED

#define AXIOM_CAPSULE_MAGIC_A 0x41u /* A */
#define AXIOM_CAPSULE_MAGIC_X 0x58u /* X */
#define AXIOM_CAPSULE_MAGIC_C 0x43u /* C */
#define AXIOM_CAPSULE_MAGIC_P 0x50u /* P */
#define AXIOM_CAPSULE_VERSION 1u
#define AXIOM_CAPSULE_HEADER_LEN 21u
#define AXIOM_CAPSULE_CRC_LEN 4u
#define AXIOM_CAPSULE_MIN_LEN (AXIOM_CAPSULE_HEADER_LEN + AXIOM_CAPSULE_CRC_LEN)

#if AXIOM_CAPSULE_PRE_EVENTS > 0
#define AXIOM_CAPSULE_PRE_STORAGE_SLOTS AXIOM_CAPSULE_PRE_EVENTS
#else
#define AXIOM_CAPSULE_PRE_STORAGE_SLOTS 1
#endif

typedef enum {
    AXIOM_CAPSULE_STATE_IDLE = 0,
    AXIOM_CAPSULE_STATE_CAPTURING,
    AXIOM_CAPSULE_STATE_FROZEN,
} axiom_capsule_state_t;

static uint8_t s_pre_frames[AXIOM_CAPSULE_PRE_STORAGE_SLOTS][AXIOM_MAX_FRAME_LEN];
static uint16_t s_pre_lens[AXIOM_CAPSULE_PRE_STORAGE_SLOTS];
static uint8_t s_pre_next;
static uint8_t s_pre_count;

static uint8_t s_frame_stream[AXIOM_CAPSULE_RING_SIZE];
static uint16_t s_frame_stream_len;
static uint8_t s_pre_window_count;
static uint8_t s_post_window_count;

static uint8_t s_snapshot[AXIOM_CAPSULE_MAX_SNAPSHOT_LEN];
static uint8_t s_snapshot_len;
static uint8_t s_reset_reason;
static uint8_t s_fault_type;
static uint32_t s_drop_count;
static axiom_capsule_state_t s_state;

static uint8_t s_ram_capsule[AXIOM_CAPSULE_MAX_IMAGE_SIZE];
static uint16_t s_ram_capsule_len;

static void capsule_u16_le(uint8_t *out, uint16_t value) {
    out[0] = (uint8_t)(value & 0xFFu);
    out[1] = (uint8_t)(value >> 8);
}

static uint16_t capsule_read_u16_le(const uint8_t *data) {
    uint16_t value = data[0];
    value = (uint16_t)(value | (uint16_t)((uint16_t)data[1] << 8u));
    return value;
}

static void capsule_u32_le(uint8_t *out, uint32_t value) {
    out[0] = (uint8_t)(value & 0xFFu);
    out[1] = (uint8_t)((value >> 8) & 0xFFu);
    out[2] = (uint8_t)((value >> 16) & 0xFFu);
    out[3] = (uint8_t)(value >> 24);
}

static void capsule_hash_be(uint8_t *out, uint32_t value) {
    out[0] = (uint8_t)(value >> 24);
    out[1] = (uint8_t)((value >> 16) & 0xFFu);
    out[2] = (uint8_t)((value >> 8) & 0xFFu);
    out[3] = (uint8_t)(value & 0xFFu);
}

static uint32_t capsule_crc32(const uint8_t *data, uint32_t len) {
    uint32_t crc = 0xFFFFFFFFu;
    for (uint32_t i = 0; i < len; ++i) {
        crc ^= data[i];
        for (uint8_t bit = 0; bit < 8u; ++bit) {
            uint32_t mask = 0u - (crc & 1u);
            crc = (crc >> 1) ^ (0xEDB88320u & mask);
        }
    }
    return ~crc;
}

static bool capsule_valid_image(const uint8_t *data, uint16_t len) {
    if (len < AXIOM_CAPSULE_MIN_LEN) {
        return false;
    }
    if (data[0] != AXIOM_CAPSULE_MAGIC_A || data[1] != AXIOM_CAPSULE_MAGIC_X ||
        data[2] != AXIOM_CAPSULE_MAGIC_C || data[3] != AXIOM_CAPSULE_MAGIC_P) {
        return false;
    }
    uint16_t encoded_len = capsule_read_u16_le(data + 5);
    if (encoded_len != len) {
        return false;
    }
    uint32_t expected = (uint32_t)data[len - 4u] |
        ((uint32_t)data[len - 3u] << 8) |
        ((uint32_t)data[len - 2u] << 16) |
        ((uint32_t)data[len - 1u] << 24);
    return capsule_crc32(data, (uint32_t)len - AXIOM_CAPSULE_CRC_LEN) == expected;
}

static bool append_frame(const uint8_t *frame, uint16_t len, bool pre_window) {
    if (!frame || len == 0u || len > AXIOM_MAX_FRAME_LEN) {
        return false;
    }
    if ((uint32_t)s_frame_stream_len + len > AXIOM_CAPSULE_RING_SIZE) {
        s_state = AXIOM_CAPSULE_STATE_FROZEN;
        return false;
    }
    memcpy(s_frame_stream + s_frame_stream_len, frame, len);
    s_frame_stream_len = (uint16_t)(s_frame_stream_len + len);
    if (pre_window) {
        if (s_pre_window_count < 255u) {
            s_pre_window_count++;
        }
    } else {
        if (s_post_window_count < 255u) {
            s_post_window_count++;
        }
    }
    return true;
}

static void store_pre_frame(const uint8_t *frame, uint16_t len) {
    if (AXIOM_CAPSULE_PRE_EVENTS == 0u || !frame || len == 0u || len > AXIOM_MAX_FRAME_LEN) {
        return;
    }
    memcpy(s_pre_frames[s_pre_next], frame, len);
    s_pre_lens[s_pre_next] = len;
    s_pre_next = (uint8_t)((s_pre_next + 1u) % AXIOM_CAPSULE_PRE_STORAGE_SLOTS);
    if (s_pre_count < AXIOM_CAPSULE_PRE_EVENTS) {
        s_pre_count++;
    }
}

static void freeze_pre_window(void) {
    uint8_t start = (s_pre_count == AXIOM_CAPSULE_PRE_EVENTS) ? s_pre_next : 0u;
    for (uint8_t i = 0; i < s_pre_count; ++i) {
        uint8_t index = (uint8_t)((start + i) % AXIOM_CAPSULE_PRE_STORAGE_SLOTS);
        if (!append_frame(s_pre_frames[index], s_pre_lens[index], true)) {
            break;
        }
    }
}

static bool build_ram_capsule(void) {
    uint32_t total_len = AXIOM_CAPSULE_HEADER_LEN + (uint32_t)s_snapshot_len +
        (uint32_t)s_frame_stream_len + AXIOM_CAPSULE_CRC_LEN;
    if (total_len > AXIOM_CAPSULE_MAX_IMAGE_SIZE || total_len > 0xFFFFu) {
        return false;
    }

    uint16_t pos = 0;
    s_ram_capsule[pos++] = AXIOM_CAPSULE_MAGIC_A;
    s_ram_capsule[pos++] = AXIOM_CAPSULE_MAGIC_X;
    s_ram_capsule[pos++] = AXIOM_CAPSULE_MAGIC_C;
    s_ram_capsule[pos++] = AXIOM_CAPSULE_MAGIC_P;
    s_ram_capsule[pos++] = AXIOM_CAPSULE_VERSION;
    capsule_u16_le(s_ram_capsule + pos, (uint16_t)total_len);
    pos = (uint16_t)(pos + 2u);
    s_ram_capsule[pos++] = s_reset_reason;
    s_ram_capsule[pos++] = s_fault_type;
    capsule_hash_be(s_ram_capsule + pos, AXIOM_CAPSULE_FIRMWARE_HASH);
    pos = (uint16_t)(pos + 4u);
    capsule_u32_le(s_ram_capsule + pos, s_drop_count);
    pos = (uint16_t)(pos + 4u);
    s_ram_capsule[pos++] = s_pre_window_count;
    s_ram_capsule[pos++] = s_post_window_count;
    s_ram_capsule[pos++] = AXIOM_CAPSULE_SNAPSHOT_ID;
    s_ram_capsule[pos++] = s_snapshot_len;
    if (s_snapshot_len > 0u) {
        memcpy(s_ram_capsule + pos, s_snapshot, s_snapshot_len);
        pos = (uint16_t)(pos + s_snapshot_len);
    }
    if (s_frame_stream_len > 0u) {
        memcpy(s_ram_capsule + pos, s_frame_stream, s_frame_stream_len);
        pos = (uint16_t)(pos + s_frame_stream_len);
    }
    uint32_t crc = capsule_crc32(s_ram_capsule, pos);
    capsule_u32_le(s_ram_capsule + pos, crc);
    pos = (uint16_t)(pos + AXIOM_CAPSULE_CRC_LEN);
    s_ram_capsule_len = pos;
    return true;
}

static bool read_flash_capsule(uint8_t *out, uint32_t max_len, uint32_t *copied) {
    uint8_t header[AXIOM_CAPSULE_HEADER_LEN];
    if (axiom_port_flash_read(AXIOM_CAPSULE_FLASH_BASE, header, sizeof(header)) < 0) {
        return false;
    }
    uint16_t len = capsule_read_u16_le(header + 5);
    if (len < AXIOM_CAPSULE_MIN_LEN || len > AXIOM_CAPSULE_MAX_IMAGE_SIZE || len > max_len) {
        return false;
    }
    if (axiom_port_flash_read(AXIOM_CAPSULE_FLASH_BASE, out, len) < 0) {
        return false;
    }
    if (!capsule_valid_image(out, len)) {
        return false;
    }
    if (copied) {
        *copied = len;
    }
    return true;
}

void axiom_capsule_init(void) {
    s_pre_next = 0;
    s_pre_count = 0;
    s_frame_stream_len = 0;
    s_pre_window_count = 0;
    s_post_window_count = 0;
    s_snapshot_len = 0;
    s_reset_reason = 0;
    s_fault_type = 0;
    s_drop_count = 0;
    s_state = AXIOM_CAPSULE_STATE_IDLE;
    s_ram_capsule_len = 0;
    memset(s_pre_lens, 0, sizeof(s_pre_lens));
}

void axiom_capsule_record_drops(uint32_t lost) {
    s_drop_count += lost;
}

void axiom_capsule_observe_frame(const uint8_t *frame, uint16_t len, axiom_level_t level) {
    if (!frame || len == 0u) {
        return;
    }

    if (s_state == AXIOM_CAPSULE_STATE_IDLE) {
        if (level == AXIOM_LEVEL_FAULT) {
            s_state = AXIOM_CAPSULE_STATE_CAPTURING;
            s_reset_reason = axiom_port_reset_reason();
            s_fault_type = frame[3];
            s_snapshot_len = axiom_port_fault_snapshot(s_snapshot, AXIOM_CAPSULE_MAX_SNAPSHOT_LEN);
            if (s_snapshot_len > AXIOM_CAPSULE_MAX_SNAPSHOT_LEN) {
                s_snapshot_len = AXIOM_CAPSULE_MAX_SNAPSHOT_LEN;
            }
            freeze_pre_window();
            (void)append_frame(frame, len, false);
            if (s_post_window_count >= AXIOM_CAPSULE_POST_EVENTS) {
                s_state = AXIOM_CAPSULE_STATE_FROZEN;
            }
        } else {
            store_pre_frame(frame, len);
        }
        return;
    }

    if (s_state == AXIOM_CAPSULE_STATE_CAPTURING) {
        if (s_post_window_count < AXIOM_CAPSULE_POST_EVENTS) {
            (void)append_frame(frame, len, false);
        }
        if (s_post_window_count >= AXIOM_CAPSULE_POST_EVENTS) {
            s_state = AXIOM_CAPSULE_STATE_FROZEN;
        }
    }
}

bool axiom_capsule_commit(void) {
    if (s_frame_stream_len == 0u) {
        return false;
    }
    if (!build_ram_capsule()) {
        return false;
    }
    int erase = axiom_port_flash_erase(AXIOM_CAPSULE_FLASH_BASE, AXIOM_CAPSULE_FLASH_SIZE);
    if (erase < 0) {
        return false;
    }
    int write = axiom_port_flash_write(AXIOM_CAPSULE_FLASH_BASE, s_ram_capsule, s_ram_capsule_len);
    return write == 0 || write == (int)s_ram_capsule_len;
}

bool axiom_capsule_present(void) {
    if (s_ram_capsule_len > 0u && capsule_valid_image(s_ram_capsule, s_ram_capsule_len)) {
        return true;
    }
    uint8_t scratch[AXIOM_CAPSULE_MAX_IMAGE_SIZE];
    uint32_t copied = 0;
    return read_flash_capsule(scratch, sizeof(scratch), &copied);
}

uint32_t axiom_capsule_read(uint8_t *out, uint32_t max_len) {
    if (!out || max_len == 0u) {
        return 0;
    }
    if (s_ram_capsule_len > 0u && s_ram_capsule_len <= max_len &&
        capsule_valid_image(s_ram_capsule, s_ram_capsule_len)) {
        memcpy(out, s_ram_capsule, s_ram_capsule_len);
        return s_ram_capsule_len;
    }
    uint32_t copied = 0;
    if (read_flash_capsule(out, max_len, &copied)) {
        return copied;
    }
    return 0;
}

void axiom_capsule_clear(void) {
    axiom_capsule_init();
    (void)axiom_port_flash_erase(AXIOM_CAPSULE_FLASH_BASE, AXIOM_CAPSULE_FLASH_SIZE);
}

#else

void axiom_capsule_init(void) { }
void axiom_capsule_observe_frame(const uint8_t *frame, uint16_t len, axiom_level_t level) {
    (void)frame;
    (void)len;
    (void)level;
}
void axiom_capsule_record_drops(uint32_t lost) { (void)lost; }
bool axiom_capsule_commit(void) { return false; }
bool axiom_capsule_present(void) { return false; }
uint32_t axiom_capsule_read(uint8_t *out, uint32_t max_len) {
    (void)out;
    (void)max_len;
    return 0;
}
void axiom_capsule_clear(void) { }

#endif

/* ===== axiom_event.c ===== */
#include <string.h>

#ifndef AXIOM_RING_BUFFER_SIZE
#define AXIOM_RING_BUFFER_SIZE 4096u
#endif

/* Compile-time sanity checks — must come AFTER all default overrides */
_Static_assert(AXIOM_MAX_PAYLOAD_LEN <= 255,
    "AXIOM_MAX_PAYLOAD_LEN must not exceed 255 (uint8_t limit)");
_Static_assert((AXIOM_RING_BUFFER_SIZE & (AXIOM_RING_BUFFER_SIZE - 1u)) == 0,
    "AXIOM_RING_BUFFER_SIZE must be a power of two");

/* ---------------------------------------------------------------------------
 * Encode overflow flag — set by axiom_enc_xxx() when payload exceeds limit.
 * Consumed and cleared by axiom_write() after each event.
 * --------------------------------------------------------------------------- */
#if AXIOM_ENCODE_OVERFLOW_DETECTION
volatile bool axiom_encode_overflow = false;
#endif

/* ---------------------------------------------------------------------------
 * Double-buffer: pre-encode into local buffer, then single ring_write.
 * This minimizes the critical section to a single memcpy+ring_write,
 * drastically reducing interrupt latency.
 *
 * Trade-off: +AXIOM_MAX_FRAME_LEN bytes of stack/RAM per axiom_write()
 * call site. Disabled via AXIOM_SHORT_CS=0 if RAM is critical.
 * --------------------------------------------------------------------------- */
#ifndef AXIOM_SHORT_CS
#define AXIOM_SHORT_CS 1
#endif

static uint8_t s_ring_buf[AXIOM_RING_BUFFER_SIZE];
static axiom_ring_t s_ring;
static uint16_t s_seq;
static axiom_filter_t s_filter;
static axiom_timestamp_ctx_t s_ts_ctx;

static void axiom_write_drop_summary(uint32_t lost, uint8_t mod, uint16_t evt) {
    uint8_t summary[7];
    uint8_t sp = 0;
    summary[sp++] = (uint8_t)(lost & 0xFFu);
    summary[sp++] = (uint8_t)((lost >> 8) & 0xFFu);
    summary[sp++] = (uint8_t)((lost >> 16) & 0xFFu);
    summary[sp++] = (uint8_t)(lost >> 24);
    summary[sp++] = mod;
    summary[sp++] = (uint8_t)(evt & 0xFFu);
    summary[sp++] = (uint8_t)(evt >> 8);
    axiom_write(AXIOM_LEVEL_WARN, AXIOM_SYSTEM_MODULE_ID, AXIOM_SYSTEM_EVENT_DROP_SUMMARY, summary, sp);
}

void axiom_init(void) {
    axiom_ring_init(&s_ring, s_ring_buf, AXIOM_RING_BUFFER_SIZE);
    s_seq = 0;
    axiom_filter_init(&s_filter);
    axiom_timestamp_init(&s_ts_ctx);
    axiom_capsule_init();
}

void axiom_flush(void) {
    uint8_t frame[AXIOM_MAX_FRAME_LEN];
    uint16_t n;
    while ((n = axiom_ring_peek(&s_ring, frame, sizeof(frame))) > 0) {
        /* Frame structure: Header(8B) + Timestamp(1-5B) + PayloadLen(1B) + Payload(N) + CRC(2B) */
        /* Minimum frame: header(8) + timestamp(1) + payload_len(1) + crc(2) = 12 */
        if (n < 12) break;
        /* Decode variable-length timestamp to find payload_len offset */
        uint8_t ts_len = axiom_timestamp_decode_len(frame[8]);
        /* Determine actual frame length */
        uint16_t payload_len = frame[8 + ts_len];
        uint16_t frame_len = (uint16_t)(8u + ts_len + 1u + payload_len + 2u);
        if (n < frame_len) break;
        /* Data already copied by peek — just advance the tail pointer */
        axiom_ring_consume(&s_ring, frame_len);
        axiom_backend_dispatch(frame, frame_len);
    }
}

/* ---------------------------------------------------------------------------
 * axiom_write() — core event emission path
 *
 * AXIOM_SHORT_CS (default=1): pre-encode frame into a local buffer
 * OUTSIDE the critical section, then perform a single ring_write
 * INSIDE the critical section. This minimizes interrupt latency.
 *
 * Frame layout in local_buf:
 *   [Header:8B] [Timestamp:1-5B] [PayloadLen:1B] [Payload:NB] [CRC:2B]
 *
 * CRC covers everything (header + timestamp + payload_len + payload),
 * matching the original per-phase write path's CRC scope.
 *
 * AXIOM_SHORT_CS=0: falls back to the original per-phase write pattern
 * for MCUs where stack usage is critical (saves AXIOM_MAX_FRAME_LEN bytes).
 * --------------------------------------------------------------------------- */
#if AXIOM_SHORT_CS

void axiom_write(axiom_level_t level, uint8_t module_id, uint16_t event_id,
                 const uint8_t *payload, uint8_t payload_len) {
    if (level >= AXIOM_LEVEL_MAX) return;

    if (!axiom_filter_check(&s_filter, level, module_id)) {
        /* CS protects drop_count read-modify-write from concurrent ISR races */
        axiom_port_critical_enter();
        axiom_filter_drop(&s_filter, module_id, event_id);
        axiom_port_critical_exit();
        return;
    }

    if (level == AXIOM_LEVEL_FAULT) {
        axiom_port_fault_hook(module_id, event_id, payload, payload_len);
    }

    /* Pre-encode everything into a local buffer (no lock needed yet). */
    uint8_t local_buf[AXIOM_MAX_FRAME_LEN];
    uint16_t pos = 0;

    /* Build header — level, module_id, event_id are read-only during CS.
     * s_seq is assigned inside the critical section to prevent duplicates
     * when two ISRs call axiom_write() concurrently. */
    local_buf[pos++] = AXIOM_SYNC_BYTE;
    local_buf[pos++] = AXIOM_WIRE_VERSION;
    local_buf[pos++] = (uint8_t)level;
    local_buf[pos++] = module_id;
    local_buf[pos++] = (uint8_t)(event_id & 0xFFu);
    local_buf[pos++] = (uint8_t)(event_id >> 8);
    /* seq[6..7] reserved — filled inside critical section */
    pos += 2u;

    /* Minimal critical section: s_seq + s_ts_ctx + s_ring are protected. */
    axiom_port_critical_enter();

    /* Assign sequence number — must be inside CS to avoid duplicate seq on ISR contention */
    local_buf[6] = (uint8_t)(s_seq & 0xFFu);
    local_buf[7] = (uint8_t)(s_seq >> 8);
    s_seq++;

    /* Timestamp encoding — must be inside CS to protect s_ts_ctx */
    uint8_t ts_len = axiom_timestamp_encode(&s_ts_ctx, local_buf + pos);
    pos += ts_len;

    /* Capacity check & policy enforcement */
    uint32_t head = s_ring.head;
    uint32_t tail = s_ring.tail;
    uint32_t cap  = s_ring.capacity;
    uint32_t used = head - tail;
    /* frame_len = header(8) + ts + payload_len(1) + payload + CRC(2) */
    uint16_t frame_len = (uint16_t)(pos + 1u + payload_len + 2u);

    if (used + frame_len > cap) {
#if AXIOM_RING_BUFFER_POLICY == AXIOM_RING_BUFFER_POLICY_DROP
        axiom_port_critical_exit();
        return;
#else
        s_ring.tail = (head + frame_len) - cap;
#endif
    }

    /* Payload length byte */
    local_buf[pos++] = payload_len;

    /* Append payload data to local_buf */
    if (payload_len > 0 && payload) {
        memcpy(local_buf + pos, payload, payload_len);
        pos += payload_len;
    }

    /* CRC covers the entire frame so far (header + timestamp + payload_len + payload).
     * This matches the original per-phase path where CRC covers all bytes. */
    uint16_t crc = axiom_crc16(local_buf, pos);

    /* Final CRC (little-endian) */
    local_buf[pos++] = (uint8_t)(crc & 0xFFu);
    local_buf[pos++] = (uint8_t)(crc >> 8);

    /* Single atomic write to ring — lock held for minimum time */
    axiom_ring_write_chunk(&s_ring, local_buf, pos, NULL);

    /* Snapshot drop statistics atomically before leaving CS */
    const bool has_drop = s_filter.drop_pending;
    uint32_t cached_lost = 0;
    uint8_t  cached_mod  = 0;
    uint16_t cached_evt  = 0;
    if (has_drop) {
        cached_lost = s_filter.drop_count;
        cached_mod  = s_filter.drop_module;
        cached_evt  = s_filter.drop_event;
        s_filter.drop_count   = 0;
        s_filter.drop_pending = false;
        s_filter.drop_module  = 0;
        s_filter.drop_event   = 0;
    }

    axiom_port_critical_exit();

    axiom_capsule_observe_frame(local_buf, pos, level);

    /* Emit DROP_SUMMARY outside critical section.
     * Recursive axiom_write() is safe: it has its own critical section.
     * Using cached_* locals avoids touching s_filter after CS exit. */
    if (has_drop) {
        axiom_capsule_record_drops(cached_lost);
        axiom_write_drop_summary(cached_lost, cached_mod, cached_evt);
    }
}

#else /* AXIOM_SHORT_CS == 0 — original per-phase write path */

void axiom_write(axiom_level_t level, uint8_t module_id, uint16_t event_id,
                 const uint8_t *payload, uint8_t payload_len) {
    if (level >= AXIOM_LEVEL_MAX) return;

    if (!axiom_filter_check(&s_filter, level, module_id)) {
        /* CS protects drop_count read-modify-write from concurrent ISR races */
        axiom_port_critical_enter();
        axiom_filter_drop(&s_filter, module_id, event_id);
        axiom_port_critical_exit();
        return;
    }

    if (level == AXIOM_LEVEL_FAULT) {
        axiom_port_fault_hook(module_id, event_id, payload, payload_len);
    }

    axiom_port_critical_enter();

    uint8_t ts_buf[5];
    uint8_t ts_len = axiom_timestamp_encode(&s_ts_ctx, ts_buf);
    uint16_t total_len = (uint16_t)(8u + ts_len + 1u + payload_len + 2u);

    uint32_t head = s_ring.head;
    uint32_t tail = s_ring.tail;
    uint32_t cap  = s_ring.capacity;
    uint32_t used = head - tail;

    if (used + total_len > cap) {
#if AXIOM_RING_BUFFER_POLICY == AXIOM_RING_BUFFER_POLICY_DROP
        axiom_port_critical_exit();
        return;
#else
        s_ring.tail = (head + total_len) - cap;
#endif
    }

    uint16_t crc = 0xFFFFu;
    uint8_t header[8];
    header[0] = AXIOM_SYNC_BYTE;
    header[1] = AXIOM_WIRE_VERSION;
    header[2] = (uint8_t)level;
    header[3] = module_id;
    header[4] = (uint8_t)(event_id & 0xFFu);
    header[5] = (uint8_t)(event_id >> 8);
    header[6] = (uint8_t)(s_seq & 0xFFu);
    header[7] = (uint8_t)(s_seq >> 8);
    s_seq++;

#if AXIOM_CAPSULE_ENABLED
    uint8_t capsule_frame[AXIOM_MAX_FRAME_LEN];
    uint16_t capsule_pos = 0;
    memcpy(capsule_frame + capsule_pos, header, sizeof(header));
    capsule_pos = (uint16_t)(capsule_pos + sizeof(header));
    memcpy(capsule_frame + capsule_pos, ts_buf, ts_len);
    capsule_pos = (uint16_t)(capsule_pos + ts_len);
#endif

    axiom_ring_write_chunk(&s_ring, header, 8, &crc);
    axiom_ring_write_chunk(&s_ring, ts_buf, ts_len, &crc);
    axiom_ring_write_chunk(&s_ring, &payload_len, 1, &crc);
#if AXIOM_CAPSULE_ENABLED
    capsule_frame[capsule_pos++] = payload_len;
#endif
    if (payload_len > 0 && payload) {
        axiom_ring_write_chunk(&s_ring, payload, payload_len, &crc);
#if AXIOM_CAPSULE_ENABLED
        memcpy(capsule_frame + capsule_pos, payload, payload_len);
        capsule_pos = (uint16_t)(capsule_pos + payload_len);
#endif
    }
    uint8_t crc_buf[2];
    crc_buf[0] = (uint8_t)(crc & 0xFFu);
    crc_buf[1] = (uint8_t)(crc >> 8);
    axiom_ring_write_chunk(&s_ring, crc_buf, 2, NULL);
#if AXIOM_CAPSULE_ENABLED
    capsule_frame[capsule_pos++] = crc_buf[0];
    capsule_frame[capsule_pos++] = crc_buf[1];
#endif

    const bool     has_drop    = s_filter.drop_pending;
    uint32_t       cached_lost = 0;
    uint8_t        cached_mod  = 0;
    uint16_t       cached_evt  = 0;
    if (has_drop) {
        cached_lost = s_filter.drop_count;
        cached_mod  = s_filter.drop_module;
        cached_evt  = s_filter.drop_event;
        s_filter.drop_count   = 0;
        s_filter.drop_pending = false;
        s_filter.drop_module  = 0;
        s_filter.drop_event   = 0;
    }

    axiom_port_critical_exit();

#if AXIOM_CAPSULE_ENABLED
    axiom_capsule_observe_frame(capsule_frame, capsule_pos, level);
#endif

    if (has_drop) {
        axiom_capsule_record_drops(cached_lost);
        axiom_write_drop_summary(cached_lost, cached_mod, cached_evt);
    }
}

#endif /* AXIOM_SHORT_CS */

/* ---------------------------------------------------------------------------
 * Runtime filter control API — operates on the global s_filter instance
 * --------------------------------------------------------------------------- */
void axiom_level_mask_set(uint32_t mask) {
    s_filter.level_mask = mask;
}

uint32_t axiom_level_mask_get(void) {
    return s_filter.level_mask;
}

void axiom_module_mask_set(uint32_t mask) {
    s_filter.module_mask = mask;
}

uint32_t axiom_module_mask_get(void) {
    return s_filter.module_mask;
}

/* ===== axiom_backend.c ===== */
#include <stdbool.h>

/* ---------------------------------------------------------------------------
 * Backend Registry & Degradation State
 * --------------------------------------------------------------------------- */
static const axiom_backend_t *s_backends[AXIOM_BACKEND_MAX];
static uint8_t s_backend_count = 0;

#if AXIOM_BACKEND_DEGRADATION
/* Per-backend degradation tracking.
 * disabled=true means the backend has exceeded AXIOM_BACKEND_FAIL_THRESHOLD
 * and will be skipped until AXIOM_BACKEND_RECOVERY_US has elapsed. */
static bool     s_be_disabled[AXIOM_BACKEND_MAX];
static uint32_t s_be_error_count[AXIOM_BACKEND_MAX];
static uint32_t s_be_disabled_at[AXIOM_BACKEND_MAX];
#endif

int axiom_backend_register(const axiom_backend_t *backend) {
    if (!backend || !backend->write) {
        return AXIOM_BACKEND_ERR_NULL;
    }
    if (s_backend_count >= AXIOM_BACKEND_MAX) {
        return AXIOM_BACKEND_ERR_FULL;
    }
    /* Backward compatibility: old backends may be zero-initialized with size==0.
     * Treat size==0 as legacy layout (v1 without the size field).
     * size > 0 but < current sizeof means a newer library compiled against
     * an older struct — reject to prevent reading garbage. */
    if (backend->size != 0 && backend->size < sizeof(axiom_backend_t)) {
        return AXIOM_BACKEND_ERR_STRUCT;
    }

#if AXIOM_BACKEND_DEGRADATION
    s_be_disabled[s_backend_count] = false;
    s_be_error_count[s_backend_count] = 0;
    s_be_disabled_at[s_backend_count] = 0;
#endif

    s_backends[s_backend_count++] = backend;
    return 0;
}

void axiom_backend_dispatch(const uint8_t *frame, uint16_t len) {
    for (uint8_t i = 0; i < s_backend_count; ++i) {
        const axiom_backend_t *be = s_backends[i];

#if AXIOM_BACKEND_DEGRADATION
        /* Auto-recovery: if recovery time has elapsed, re-enable backend.
         * Handles 32-bit timestamp overflow via unsigned subtraction:
         * (now - disabled_at) correctly wraps on overflow. */
        if (s_be_disabled[i]) {
            uint32_t now = axiom_port_timestamp();
            uint32_t elapsed = now - s_be_disabled_at[i];
            if (elapsed >= AXIOM_BACKEND_RECOVERY_US) {
                s_be_disabled[i] = false;
                s_be_error_count[i] = 0;
            } else {
                continue; /* still in recovery window — skip */
            }
        }
#endif

        if (be->ready && !be->ready(be->ctx)) {
            if (be->on_drop) {
                be->on_drop(1, be->ctx);
            }
            continue;
        }
        int ret = be->write(frame, len, be->ctx);
        if (ret < 0 && be->on_drop) {
            be->on_drop(1, be->ctx);
        }

#if AXIOM_BACKEND_DEGRADATION
        if (ret < 0) {
            s_be_error_count[i]++;
            if (s_be_error_count[i] >= AXIOM_BACKEND_FAIL_THRESHOLD) {
                s_be_disabled[i] = true;
                s_be_disabled_at[i] = axiom_port_timestamp();
            }
        } else {
            s_be_error_count[i] = 0;
        }
#endif
    }
}

void axiom_backend_flush_all(void) {
    for (uint8_t i = 0; i < s_backend_count; ++i) {
        const axiom_backend_t *be = s_backends[i];
        if (be->flush) {
            (void)be->flush(be->ctx);
        }
    }
}

void axiom_backend_panic_write(const uint8_t *frame, uint16_t len) {
    /* Panic bypasses degradation — always attempt all backends.
     * A backend that is broken in normal mode may still work for
     * panic output (e.g., SWO may be functional while UART is not). */
    for (uint8_t i = 0; i < s_backend_count; ++i) {
        const axiom_backend_t *be = s_backends[i];
        if (be->panic_write) {
            (void)be->panic_write(frame, len, be->ctx);
        } else if (be->write) {
            (void)be->write(frame, len, be->ctx);
        }
    }
}

uint8_t axiom_backend_active_count(void) {
    uint8_t active = 0;
    for (uint8_t i = 0; i < s_backend_count; ++i) {
#if AXIOM_BACKEND_DEGRADATION
        if (!s_be_disabled[i]) {
            active++;
        }
#else
        active++;
#endif
    }
    return active;
}

uint8_t axiom_backend_count(void) {
    return s_backend_count;
}

#ifdef __cplusplus
}
#endif

#endif /* AXIOMTRACE_H */
