#!/usr/bin/env python3
"""Generate the distributable AxiomTrace single-header library."""

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ROOT = REPO / "baremetal"

HEADERS = [
    ROOT / "include" / "axiom_static_assert.h",
    ROOT / "axiom_config.h",
    ROOT / "port" / "axiom_port.h",
    ROOT / "core" / "axiom_event.h",
    ROOT / "core" / "axiom_diagnostics.h",
    ROOT / "core" / "axiom_encode.h",
    ROOT / "core" / "axiom_crc.h",
    ROOT / "core" / "axiom_ring.h",
    ROOT / "core" / "axiom_timestamp.h",
    ROOT / "core" / "axiom_filter.h",
    ROOT / "core" / "axiom_frame.h",
    ROOT / "core" / "axiom_capsule.h",
    ROOT / "core" / "axiom_selftest.h",
    ROOT / "frontend" / "axiom_frontend.h",
    ROOT / "backend" / "axiom_backend.h",
    ROOT / "backend" / "axiom_backend_deferred.h",
]

SOURCES = [
    ROOT / "core" / "axiom_crc.c",
    ROOT / "core" / "axiom_ring.c",
    ROOT / "core" / "axiom_timestamp.c",
    ROOT / "core" / "axiom_filter.c",
    ROOT / "core" / "axiom_diagnostics.c",
    ROOT / "core" / "axiom_capsule.c",
    ROOT / "core" / "axiom_event.c",
    ROOT / "core" / "axiom_selftest.c",
    ROOT / "backend" / "axiom_backend.c",
    ROOT / "backend" / "axiom_backend_memory.c",
    ROOT / "backend" / "axiom_backend_deferred.c",
]

DEFAULT_PORT = ROOT / "ports" / "generic" / "axiom_port_generic.c"


def strip_local_includes(content: str, inlined_names: set[str]) -> str:
    lines = []
    for line in content.splitlines(keepends=True):
        match = re.match(r'\s*#include\s+"([^"]+)"', line)
        if match and match.group(1) in inlined_names:
            continue
        lines.append(line)
    return "".join(lines)


def generate(output: Path) -> None:
    inlined_names = {path.name for path in HEADERS}
    parts = [
        "/* Auto-generated by tool/scripts/amalgamate.py. Do not edit. */\n",
        "#ifndef AXIOMTRACE_SINGLE_HEADER_H\n",
        "#define AXIOMTRACE_SINGLE_HEADER_H\n\n",
    ]

    for path in HEADERS:
        parts.append(f"/* ===== {path.name} ===== */\n")
        parts.append(strip_local_includes(path.read_text(encoding="utf-8"), inlined_names))
        parts.append("\n")

    parts.append("#ifdef AXIOMTRACE_IMPLEMENTATION\n")
    parts.append("#ifndef AXIOMTRACE_IMPLEMENTATION_ONCE\n")
    parts.append("#define AXIOMTRACE_IMPLEMENTATION_ONCE\n\n")
    parts.append("#ifndef AXIOMTRACE_NO_DEFAULT_PORT\n")
    parts.append("/* ===== generic default port ===== */\n")
    parts.append(strip_local_includes(DEFAULT_PORT.read_text(encoding="utf-8"), inlined_names))
    parts.append("\n#endif /* AXIOMTRACE_NO_DEFAULT_PORT */\n\n")

    for path in SOURCES:
        parts.append(f"/* ===== {path.name} ===== */\n")
        parts.append(strip_local_includes(path.read_text(encoding="utf-8"), inlined_names))
        parts.append("\n")

    parts.append("#endif /* AXIOMTRACE_IMPLEMENTATION_ONCE */\n")
    parts.append("#endif /* AXIOMTRACE_IMPLEMENTATION */\n\n")
    parts.append("#endif /* AXIOMTRACE_SINGLE_HEADER_H */\n")

    result = "".join(parts)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(result, encoding="utf-8")
    print(f"Generated {output} ({len(result)} bytes)")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=REPO / "dist" / "axiomtrace.h")
    args = parser.parse_args()
    generate(args.output.resolve())


if __name__ == "__main__":
    main()
